version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Asia/Jerusalem"
    open-pull-requests-limit: 6
    versioning-strategy: "increase"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    groups:
      production-minor-patch:
        applies-to: "version-updates"
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
      development-minor-patch:
        applies-to: "version-updates"
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "06:00"
      timezone: "Asia/Jerusalem"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "ci-deps"
      include: "scope"
    groups:
      actions-minor-patch:
        applies-to: "version-updates"
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
