"use client";
import { useEffect,useRef,useState } from 'react';
import type { InterfaceLanguage } from '../../shared/domain/businessProfileDraft.ts';
import type { MetaMediaCleanupRequestStatus } from '../../shared/domain/metaMediaCleanup.ts';
export const mediaCleanupMessages={
  he:{label:'הסרת עותק הקובץ מהמערכת',detail:'עותק המדיה שנשמר במערכת יוסר לצמיתות. ההודעה ורישומי הבדיקה יישמרו. הגישה לקובץ תיחסם מיד עם קליטת הבקשה.',confirm:'אישור הסרת עותק הקובץ',cancel:'ביטול',pending:'רושם בקשת הסרה…',queued:'בקשת ההסרה נרשמה והגישה נחסמה. רעננו בהמשך כדי לבדוק את תוצאת ההסרה.',
    'already-requested':'בקשת ההסרה כבר נרשמה. רעננו את המצב.','permission-denied':'אין הרשאה להסיר את העותק כעת.',conflict:'מצב המשימה השתנה או שאינו מאפשר הסרה. רעננו את המצב.','invalid-request':'הבקשה אינה תקינה. רעננו את העמוד.','configuration-required':'יש להשלים את הגדרת השירות.','server-error':'לא ניתן לאמת את קליטת הבקשה. אפשר לנסות שוב; אותה בקשה לא תירשם פעמיים.',states:{pending:'הסרת העותק ממתינה',running:'הסרת העותק מתבצעת',removed:'S3 אישר את הסרת גרסת הקובץ',cancelled:'ההסרה בוטלה; הגישה לעותק נשארת חסומה','recovery-required':'תוצאת ההסרה דורשת בירור; הגישה נשארת חסומה'}},
  en:{label:'Remove the stored file copy',detail:'The media copy stored in this system will be permanently removed. The message and inspection records will remain. Access is blocked as soon as the request is recorded.',confirm:'Confirm removal of the file copy',cancel:'Cancel',pending:'Recording removal request…',queued:'Removal was requested and access was blocked. Refresh later to check the removal result.',
    'already-requested':'Removal was already requested. Refresh the status.','permission-denied':'You cannot remove this copy right now.',conflict:'The task changed or is not eligible for removal. Refresh the status.','invalid-request':'The request is invalid. Refresh the page.','configuration-required':'Service configuration is required.','server-error':'Could not confirm the request. You can retry; the same request will not be recorded twice.',states:{pending:'Copy removal is pending',running:'Copy removal is in progress',removed:'S3 acknowledged removal of the file version',cancelled:'Removal was cancelled; access remains blocked','recovery-required':'Removal needs investigation; access remains blocked'}},
  ar:{label:'إزالة نسخة الملف المحفوظة',detail:'ستُزال نسخة الوسائط المحفوظة في النظام نهائيًا. ستبقى الرسالة وسجلات الفحص. يُحظر الوصول بمجرد تسجيل الطلب.',confirm:'تأكيد إزالة نسخة الملف',cancel:'إلغاء',pending:'جارٍ تسجيل طلب الإزالة…',queued:'سُجّل طلب الإزالة وحُظر الوصول. حدّث الحالة لاحقًا للتحقق من نتيجة الإزالة.',
    'already-requested':'سُجّل طلب الإزالة مسبقًا. حدّث الحالة.','permission-denied':'لا تملك صلاحية إزالة هذه النسخة حاليًا.',conflict:'تغيّرت المهمة أو لا تسمح بالإزالة. حدّث الحالة.','invalid-request':'الطلب غير صالح. حدّث الصفحة.','configuration-required':'يلزم إكمال إعداد الخدمة.','server-error':'تعذر تأكيد تسجيل الطلب. يمكنك المحاولة مجددًا؛ لن يُسجّل الطلب نفسه مرتين.',states:{pending:'إزالة النسخة قيد الانتظار',running:'جارٍ إزالة النسخة',removed:'أكّد S3 إزالة إصدار الملف',cancelled:'أُلغيت الإزالة؛ يظل الوصول محظورًا','recovery-required':'تحتاج الإزالة إلى مراجعة؛ يظل الوصول محظورًا'}},
} as const;
const results=['queued','already-requested','permission-denied','conflict','invalid-request','configuration-required','server-error'];
export function MetaMediaCleanupControl({language,jobKey,expectedVersion,requestCleanup}:{language:InterfaceLanguage;jobKey:string;expectedVersion:number;requestCleanup:(input:unknown)=>Promise<MetaMediaCleanupRequestStatus>}){
  const [status,setStatus]=useState<'idle'|'confirm'|'pending'|MetaMediaCleanupRequestStatus>('idle'),active=useRef(false),mounted=useRef(false);
  useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;};},[]);
  const text=mediaCleanupMessages[language];
  async function submit(){if(active.current)return;active.current=true;setStatus('pending');try{const result=await requestCleanup({jobKey,expectedVersion,confirm:'remove-quarantined-copy'});if(mounted.current)setStatus(results.includes(result)?result:'server-error');}catch{if(mounted.current)setStatus('server-error');}finally{active.current=false;}}
  return <section className="media-cleanup-control" aria-busy={status==='pending'}>
    {status==='confirm'?<><p>{text.detail}</p><div className="media-diagnostics-actions"><button type="button" className="secondary-button" onClick={()=>{void submit();}}>{text.confirm}</button><button type="button" className="secondary-button" onClick={()=>setStatus('idle')}>{text.cancel}</button></div></>:
      <button type="button" className="secondary-button" disabled={['pending','queued','already-requested'].includes(status)} onClick={()=>setStatus('confirm')}>{status==='pending'?text.pending:text.label}</button>}
    <p role="status">{status==='idle'||status==='confirm'||status==='pending'?'':text[status]}</p>
  </section>;
}
