import assert from "node:assert/strict";
import {
  readFileSync,
  readdirSync,
} from "node:fs";
import test from "node:test";

import {
  inspectPostgresMigrationContract,
  validatePostgresMigrationSources,
} from "../scripts/verify-postgres-migration-contract.mjs";

const migrationsUrl = new URL(
  "../postgres/migrations/",
  import.meta.url,
);
const migrationFiles = readdirSync(migrationsUrl)
  .filter((fileName) => fileName.endsWith(".sql"))
  .sort();
const migrationSources = migrationFiles.map((fileName) =>
  readFileSync(new URL(fileName, migrationsUrl), "utf8"),
);
const coreSchema = migrationSources[0];
const accessSchema = migrationSources[2];

test("keeps the PostgreSQL critical-path migration inventory ordered", async () => {
  assert.deepEqual(migrationFiles, [
    "0000_core_contacts.sql",
    "0001_railway_api_mutation_receipts.sql",
    "0002_tenant_access_foundation.sql",
  ]);
  assert.deepEqual(
    await inspectPostgresMigrationContract(),
    {
      status: "passed",
      migrationCount: 3,
      findings: [],
    },
  );
});

test("defines tenant, audit, and contact prerequisites with PostgreSQL-native types", () => {
  assert.match(
    coreSchema,
    /CREATE TABLE tenants[\s\S]*id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY/,
  );
  assert.match(
    coreSchema,
    /CREATE TABLE audit_logs[\s\S]*metadata_json JSONB/,
  );
  assert.match(
    coreSchema,
    /CREATE TABLE contacts[\s\S]*consent_recorded_at TIMESTAMPTZ/,
  );
  assert.match(
    coreSchema,
    /created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP/,
  );
  assert.match(
    coreSchema,
    /contacts_tenant_phone_uq[\s\S]*UNIQUE \(tenant_id, phone_e164\)/,
  );
  assert.match(
    coreSchema,
    /contacts_phone_e164_valid[\s\S]*phone_e164 ~ '\^\\\+\[1-9\]\[0-9\]\{0,14\}\$'/,
  );
});

test("scopes audit idempotency to tenant and action", () => {
  assert.match(
    coreSchema,
    /audit_logs_tenant_action_idempotency_uq[\s\S]*\(tenant_id, action, idempotency_key\)[\s\S]*WHERE idempotency_key IS NOT NULL/,
  );
  assert.doesNotMatch(
    coreSchema,
    /UNIQUE\s*\(idempotency_key\)/,
  );
});

test("defines tenant access isolation and exact membership version transitions", () => {
  assert.match(
    accessSchema,
    /CREATE TABLE tenant_memberships[\s\S]*UNIQUE \(tenant_id, external_user_id\)/,
  );
  assert.match(
    accessSchema,
    /CREATE TABLE tenant_selections[\s\S]*FOREIGN KEY \(tenant_id, external_user_id\)[\s\S]*REFERENCES tenant_memberships \(tenant_id, external_user_id\)[\s\S]*ON DELETE CASCADE/,
  );
  assert.match(
    accessSchema,
    /CREATE TRIGGER tenant_memberships_state_version_guard[\s\S]*BEFORE UPDATE OF role, status, version/,
  );
  assert.match(
    accessSchema,
    /NEW\.version <> OLD\.version \+ 1/,
  );
  assert.match(
    accessSchema,
    /CREATE TABLE business_profiles[\s\S]*interface_language IN \('he', 'en', 'ar'\)/,
  );
});

test("rejects missing prerequisites and SQLite migration syntax", () => {
  const sources = [
    "CREATE TABLE tenants (id BIGINT);",
    "CREATE TABLE audit_logs (id BIGINT);",
  ];
  const findings = validatePostgresMigrationSources({
    migrationFiles: [
      "0000_core_contacts.sql",
      "0002_wrong_sequence.sql",
    ],
    sources: [
      sources[0],
      `${sources[1]} PRAGMA foreign_keys = ON;`,
    ],
  });
  const codes = findings.map(({ code }) => code);

  assert.equal(
    codes.includes("POSTGRES_REQUIRED_MIGRATION_PREFIX_INVALID"),
    true,
  );
  assert.equal(
    codes.includes("POSTGRES_MIGRATION_SEQUENCE_INVALID"),
    true,
  );
  assert.equal(
    codes.includes("POSTGRES_SQLITE_PRAGMA"),
    true,
  );
  assert.equal(
    codes.includes("POSTGRES_REQUIRED_TABLE_SEQUENCE_INVALID"),
    true,
  );
});

test("rejects destructive, seeded, and random-identity migrations", () => {
  const findings = validatePostgresMigrationSources({
    migrationFiles: [
      "0000_core_contacts.sql",
      "0001_railway_api_mutation_receipts.sql",
    ],
    sources: [
      [
        "CREATE TABLE tenants (id BIGINT);",
        "CREATE TABLE audit_logs (id BIGINT);",
        "CREATE TABLE contacts (id BIGINT);",
      ].join("\n"),
      [
        "CREATE TABLE railway_api_mutation_receipts (id BIGINT);",
        "INSERT INTO railway_api_mutation_receipts (id) VALUES (1);",
        "DELETE FROM railway_api_mutation_receipts;",
        "SELECT gen_random_uuid();",
      ].join("\n"),
    ],
  });
  const codes = findings.map(({ code }) => code);

  assert.equal(codes.includes("POSTGRES_SEED_DATA_PRESENT"), true);
  assert.equal(
    codes.includes("POSTGRES_DESTRUCTIVE_STATEMENT"),
    true,
  );
  assert.equal(codes.includes("POSTGRES_RANDOM_IDENTITY"), true);
});
