-- PostgreSQL critical-path schema for the first Railway mutation.
-- This migration intentionally contains no seed or demonstration data.

CREATE TABLE tenants (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provisioning_key TEXT,
  display_name TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'trial',
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT tenants_display_name_not_blank
    CHECK (length(btrim(display_name)) > 0),
  CONSTRAINT tenants_status_valid
    CHECK (
      status IN (
        'trial',
        'active',
        'payment_failed',
        'suspended',
        'cancelled',
        'expired',
        'blocked'
      )
    )
);

CREATE UNIQUE INDEX tenants_provisioning_key_uq
  ON tenants (provisioning_key);

CREATE INDEX tenants_status_idx
  ON tenants (status);

CREATE TABLE audit_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  actor_external_user_id TEXT,
  action TEXT NOT NULL,
  target_type TEXT NOT NULL,
  target_id TEXT,
  idempotency_key TEXT,
  metadata_json JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT audit_logs_tenant_fk
    FOREIGN KEY (tenant_id)
    REFERENCES tenants (id)
    ON DELETE RESTRICT,
  CONSTRAINT audit_logs_action_not_blank
    CHECK (length(btrim(action)) > 0),
  CONSTRAINT audit_logs_target_type_not_blank
    CHECK (length(btrim(target_type)) > 0)
);

CREATE INDEX audit_logs_tenant_created_idx
  ON audit_logs (tenant_id, created_at);

CREATE UNIQUE INDEX audit_logs_tenant_action_idempotency_uq
  ON audit_logs (tenant_id, action, idempotency_key)
  WHERE idempotency_key IS NOT NULL;

CREATE TABLE contacts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  phone_e164 TEXT NOT NULL,
  first_name TEXT,
  last_name TEXT,
  email TEXT,
  company TEXT,
  mailing_status TEXT NOT NULL DEFAULT 'unsubscribed',
  consent_status TEXT NOT NULL DEFAULT 'unknown',
  consent_source TEXT,
  consent_recorded_at TIMESTAMPTZ,
  consent_withdrawn_at TIMESTAMPTZ,
  consent_evidence_reference TEXT,
  version INTEGER NOT NULL DEFAULT 1,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT contacts_tenant_fk
    FOREIGN KEY (tenant_id)
    REFERENCES tenants (id)
    ON DELETE CASCADE,
  CONSTRAINT contacts_phone_e164_valid
    CHECK (phone_e164 ~ '^\+[1-9][0-9]{0,14}$'),
  CONSTRAINT contacts_mailing_status_valid
    CHECK (mailing_status IN ('subscribed', 'unsubscribed')),
  CONSTRAINT contacts_consent_status_valid
    CHECK (consent_status IN ('unknown', 'granted', 'withdrawn')),
  CONSTRAINT contacts_consent_state_consistent
    CHECK (
      (
        consent_status = 'unknown'
        AND mailing_status = 'unsubscribed'
        AND consent_source IS NULL
        AND consent_recorded_at IS NULL
        AND consent_withdrawn_at IS NULL
      )
      OR
      (
        consent_status = 'granted'
        AND mailing_status = 'subscribed'
        AND consent_source IS NOT NULL
        AND consent_recorded_at IS NOT NULL
        AND consent_withdrawn_at IS NULL
      )
      OR
      (
        consent_status = 'withdrawn'
        AND mailing_status = 'unsubscribed'
        AND consent_source IS NOT NULL
        AND consent_recorded_at IS NOT NULL
        AND consent_withdrawn_at IS NOT NULL
      )
    ),
  CONSTRAINT contacts_version_positive
    CHECK (version >= 1),
  CONSTRAINT contacts_tenant_id_uq
    UNIQUE (tenant_id, id),
  CONSTRAINT contacts_tenant_phone_uq
    UNIQUE (tenant_id, phone_e164)
);

CREATE INDEX contacts_tenant_updated_idx
  ON contacts (tenant_id, updated_at);

CREATE INDEX contacts_tenant_id_idx
  ON contacts (tenant_id, id);

CREATE INDEX contacts_tenant_mailing_idx
  ON contacts (tenant_id, mailing_status);
