-- PostgreSQL tenant access foundation for Railway authorization.
-- This migration intentionally contains no seed or demonstration data.

CREATE TABLE tenant_memberships (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  external_user_id TEXT NOT NULL,
  role TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'active',
  version INTEGER NOT NULL DEFAULT 1,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT tenant_memberships_tenant_fk
    FOREIGN KEY (tenant_id)
    REFERENCES tenants (id)
    ON DELETE CASCADE,
  CONSTRAINT tenant_memberships_external_user_id_valid
    CHECK (
      length(external_user_id) BETWEEN 1 AND 512
      AND external_user_id = btrim(external_user_id)
      AND external_user_id !~ '[[:cntrl:]]'
    ),
  CONSTRAINT tenant_memberships_role_valid
    CHECK (role IN ('owner', 'manager', 'agent', 'viewer')),
  CONSTRAINT tenant_memberships_status_valid
    CHECK (status IN ('active', 'suspended')),
  CONSTRAINT tenant_memberships_version_positive
    CHECK (version >= 1),
  CONSTRAINT tenant_memberships_tenant_user_uq
    UNIQUE (tenant_id, external_user_id)
);

CREATE INDEX tenant_memberships_user_idx
  ON tenant_memberships (external_user_id);

CREATE FUNCTION enforce_tenant_membership_state_version()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $function$
BEGIN
  IF (
    (
      NEW.role IS DISTINCT FROM OLD.role
      OR NEW.status IS DISTINCT FROM OLD.status
    )
    AND NEW.version <> OLD.version + 1
  ) OR (
    NEW.role IS NOT DISTINCT FROM OLD.role
    AND NEW.status IS NOT DISTINCT FROM OLD.status
    AND NEW.version <> OLD.version
  ) THEN
    RAISE EXCEPTION
      USING
        ERRCODE = '23514',
        MESSAGE = 'tenant membership state requires an exact version transition';
  END IF;

  RETURN NEW;
END;
$function$;

CREATE TRIGGER tenant_memberships_state_version_guard
BEFORE UPDATE OF role, status, version
ON tenant_memberships
FOR EACH ROW
EXECUTE FUNCTION enforce_tenant_membership_state_version();

CREATE TABLE tenant_selections (
  external_user_id TEXT PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  version INTEGER NOT NULL DEFAULT 1,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT tenant_selections_external_user_id_valid
    CHECK (
      length(external_user_id) BETWEEN 1 AND 512
      AND external_user_id = btrim(external_user_id)
      AND external_user_id !~ '[[:cntrl:]]'
    ),
  CONSTRAINT tenant_selections_version_positive
    CHECK (version >= 1),
  CONSTRAINT tenant_selections_membership_fk
    FOREIGN KEY (tenant_id, external_user_id)
    REFERENCES tenant_memberships (tenant_id, external_user_id)
    ON DELETE CASCADE
);

CREATE INDEX tenant_selections_tenant_idx
  ON tenant_selections (tenant_id);

CREATE TABLE business_profiles (
  tenant_id BIGINT PRIMARY KEY,
  business_name TEXT NOT NULL,
  timezone TEXT NOT NULL,
  interface_language TEXT NOT NULL,
  version INTEGER NOT NULL DEFAULT 1,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT business_profiles_tenant_fk
    FOREIGN KEY (tenant_id)
    REFERENCES tenants (id)
    ON DELETE CASCADE,
  CONSTRAINT business_profiles_business_name_not_blank
    CHECK (length(btrim(business_name)) > 0),
  CONSTRAINT business_profiles_timezone_not_blank
    CHECK (length(btrim(timezone)) > 0),
  CONSTRAINT business_profiles_language_valid
    CHECK (interface_language IN ('he', 'en', 'ar')),
  CONSTRAINT business_profiles_version_positive
    CHECK (version >= 1)
);
