-- PostgreSQL contact organization and resumable import persistence.
-- This migration intentionally contains no seed or demonstration data.

CREATE TABLE contact_tags (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  name TEXT NOT NULL,
  normalized_name TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL
    DEFAULT date_trunc('milliseconds', CURRENT_TIMESTAMP),
  updated_at TIMESTAMPTZ NOT NULL
    DEFAULT date_trunc('milliseconds', CURRENT_TIMESTAMP),
  CONSTRAINT contact_tags_tenant_fk
    FOREIGN KEY (tenant_id)
    REFERENCES tenants (id)
    ON DELETE CASCADE,
  CONSTRAINT contact_tags_name_valid
    CHECK (
      length(btrim(name)) > 0
      AND name = btrim(name)
    ),
  CONSTRAINT contact_tags_normalized_name_valid
    CHECK (
      length(btrim(normalized_name)) > 0
      AND normalized_name = btrim(normalized_name)
    ),
  CONSTRAINT contact_tags_timestamps_valid
    CHECK (
      created_at = date_trunc('milliseconds', created_at)
      AND updated_at = date_trunc('milliseconds', updated_at)
      AND updated_at >= created_at
    ),
  CONSTRAINT contact_tags_tenant_id_uq
    UNIQUE (tenant_id, id),
  CONSTRAINT contact_tags_tenant_name_uq
    UNIQUE (tenant_id, normalized_name)
);

CREATE INDEX contact_tags_tenant_created_idx
  ON contact_tags (tenant_id, created_at);

CREATE TABLE contact_lists (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  name TEXT NOT NULL,
  normalized_name TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL
    DEFAULT date_trunc('milliseconds', CURRENT_TIMESTAMP),
  updated_at TIMESTAMPTZ NOT NULL
    DEFAULT date_trunc('milliseconds', CURRENT_TIMESTAMP),
  CONSTRAINT contact_lists_tenant_fk
    FOREIGN KEY (tenant_id)
    REFERENCES tenants (id)
    ON DELETE CASCADE,
  CONSTRAINT contact_lists_name_valid
    CHECK (
      length(btrim(name)) > 0
      AND name = btrim(name)
    ),
  CONSTRAINT contact_lists_normalized_name_valid
    CHECK (
      length(btrim(normalized_name)) > 0
      AND normalized_name = btrim(normalized_name)
    ),
  CONSTRAINT contact_lists_timestamps_valid
    CHECK (
      created_at = date_trunc('milliseconds', created_at)
      AND updated_at = date_trunc('milliseconds', updated_at)
      AND updated_at >= created_at
    ),
  CONSTRAINT contact_lists_tenant_id_uq
    UNIQUE (tenant_id, id),
  CONSTRAINT contact_lists_tenant_name_uq
    UNIQUE (tenant_id, normalized_name)
);

CREATE INDEX contact_lists_tenant_created_idx
  ON contact_lists (tenant_id, created_at);

CREATE TABLE contact_tag_assignments (
  tenant_id BIGINT NOT NULL,
  contact_id BIGINT NOT NULL,
  tag_id BIGINT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL
    DEFAULT date_trunc('milliseconds', CURRENT_TIMESTAMP),
  CONSTRAINT contact_tag_assignments_tenant_fk
    FOREIGN KEY (tenant_id)
    REFERENCES tenants (id)
    ON DELETE CASCADE,
  CONSTRAINT contact_tag_assignments_contact_fk
    FOREIGN KEY (tenant_id, contact_id)
    REFERENCES contacts (tenant_id, id)
    ON DELETE CASCADE,
  CONSTRAINT contact_tag_assignments_tag_fk
    FOREIGN KEY (tenant_id, tag_id)
    REFERENCES contact_tags (tenant_id, id)
    ON DELETE CASCADE,
  CONSTRAINT contact_tag_assignments_created_at_milliseconds
    CHECK (created_at = date_trunc('milliseconds', created_at)),
  CONSTRAINT contact_tag_assignments_pk
    PRIMARY KEY (tenant_id, contact_id, tag_id)
);

CREATE INDEX contact_tag_assignments_tenant_tag_idx
  ON contact_tag_assignments (tenant_id, tag_id, contact_id);

CREATE TABLE contact_list_memberships (
  tenant_id BIGINT NOT NULL,
  contact_id BIGINT NOT NULL,
  list_id BIGINT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL
    DEFAULT date_trunc('milliseconds', CURRENT_TIMESTAMP),
  CONSTRAINT contact_list_memberships_tenant_fk
    FOREIGN KEY (tenant_id)
    REFERENCES tenants (id)
    ON DELETE CASCADE,
  CONSTRAINT contact_list_memberships_contact_fk
    FOREIGN KEY (tenant_id, contact_id)
    REFERENCES contacts (tenant_id, id)
    ON DELETE CASCADE,
  CONSTRAINT contact_list_memberships_list_fk
    FOREIGN KEY (tenant_id, list_id)
    REFERENCES contact_lists (tenant_id, id)
    ON DELETE CASCADE,
  CONSTRAINT contact_list_memberships_created_at_milliseconds
    CHECK (created_at = date_trunc('milliseconds', created_at)),
  CONSTRAINT contact_list_memberships_pk
    PRIMARY KEY (tenant_id, contact_id, list_id)
);

CREATE INDEX contact_list_memberships_tenant_list_idx
  ON contact_list_memberships (tenant_id, list_id, contact_id);

CREATE TABLE contact_import_jobs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  idempotency_key TEXT NOT NULL,
  file_name TEXT NOT NULL,
  total_rows INTEGER NOT NULL,
  processed_rows INTEGER NOT NULL DEFAULT 0,
  created_rows INTEGER NOT NULL DEFAULT 0,
  updated_rows INTEGER NOT NULL DEFAULT 0,
  unchanged_rows INTEGER NOT NULL DEFAULT 0,
  rejected_rows INTEGER NOT NULL DEFAULT 0,
  duplicate_rows INTEGER NOT NULL DEFAULT 0,
  status TEXT NOT NULL DEFAULT 'processing',
  created_by_external_user_id TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL
    DEFAULT date_trunc('milliseconds', CURRENT_TIMESTAMP),
  updated_at TIMESTAMPTZ NOT NULL
    DEFAULT date_trunc('milliseconds', CURRENT_TIMESTAMP),
  completed_at TIMESTAMPTZ,
  CONSTRAINT contact_import_jobs_tenant_fk
    FOREIGN KEY (tenant_id)
    REFERENCES tenants (id)
    ON DELETE CASCADE,
  CONSTRAINT contact_import_jobs_idempotency_key_valid
    CHECK (idempotency_key ~ '^contact_import_v1_[0-9a-f]{64}$'),
  CONSTRAINT contact_import_jobs_file_name_valid
    CHECK (
      length(file_name) BETWEEN 1 AND 255
      AND file_name = btrim(file_name)
      AND file_name !~ '[[:cntrl:]]'
      AND lower(file_name) ~ '\.(csv|xlsx)$'
    ),
  CONSTRAINT contact_import_jobs_total_rows_valid
    CHECK (total_rows BETWEEN 1 AND 50000),
  CONSTRAINT contact_import_jobs_counts_valid
    CHECK (
      processed_rows BETWEEN 0 AND total_rows
      AND created_rows BETWEEN 0 AND total_rows
      AND updated_rows BETWEEN 0 AND total_rows
      AND unchanged_rows BETWEEN 0 AND total_rows
      AND rejected_rows BETWEEN 0 AND total_rows
      AND duplicate_rows BETWEEN 0 AND total_rows
      AND processed_rows = created_rows
        + updated_rows
        + unchanged_rows
        + rejected_rows
        + duplicate_rows
    ),
  CONSTRAINT contact_import_jobs_status_valid
    CHECK (status IN ('processing', 'completed')),
  CONSTRAINT contact_import_jobs_completion_consistent
    CHECK (
      (
        status = 'processing'
        AND processed_rows < total_rows
        AND completed_at IS NULL
      )
      OR
      (
        status = 'completed'
        AND processed_rows = total_rows
        AND completed_at IS NOT NULL
      )
    ),
  CONSTRAINT contact_import_jobs_actor_valid
    CHECK (
      length(created_by_external_user_id) BETWEEN 1 AND 512
      AND created_by_external_user_id = btrim(created_by_external_user_id)
      AND created_by_external_user_id !~ '[[:cntrl:]]'
    ),
  CONSTRAINT contact_import_jobs_timestamps_valid
    CHECK (
      created_at = date_trunc('milliseconds', created_at)
      AND updated_at = date_trunc('milliseconds', updated_at)
      AND (
        completed_at IS NULL
        OR completed_at = date_trunc('milliseconds', completed_at)
      )
      AND updated_at >= created_at
      AND (completed_at IS NULL OR completed_at >= created_at)
    ),
  CONSTRAINT contact_import_jobs_tenant_id_uq
    UNIQUE (tenant_id, id),
  CONSTRAINT contact_import_jobs_tenant_key_uq
    UNIQUE (tenant_id, idempotency_key)
);

CREATE INDEX contact_import_jobs_tenant_created_idx
  ON contact_import_jobs (tenant_id, created_at, id);

CREATE TABLE contact_import_rows (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  job_id BIGINT NOT NULL,
  source_row_number INTEGER NOT NULL,
  contact_id BIGINT,
  phone_fingerprint TEXT,
  status TEXT NOT NULL,
  reason TEXT,
  created_at TIMESTAMPTZ NOT NULL
    DEFAULT date_trunc('milliseconds', CURRENT_TIMESTAMP),
  CONSTRAINT contact_import_rows_tenant_fk
    FOREIGN KEY (tenant_id)
    REFERENCES tenants (id)
    ON DELETE CASCADE,
  CONSTRAINT contact_import_rows_job_fk
    FOREIGN KEY (tenant_id, job_id)
    REFERENCES contact_import_jobs (tenant_id, id)
    ON DELETE CASCADE,
  CONSTRAINT contact_import_rows_contact_fk
    FOREIGN KEY (tenant_id, contact_id)
    REFERENCES contacts (tenant_id, id)
    ON DELETE SET NULL (contact_id),
  CONSTRAINT contact_import_rows_source_row_valid
    CHECK (source_row_number BETWEEN 2 AND 50001),
  CONSTRAINT contact_import_rows_phone_fingerprint_valid
    CHECK (
      phone_fingerprint IS NULL
      OR phone_fingerprint ~ '^[0-9a-f]{64}$'
    ),
  CONSTRAINT contact_import_rows_status_valid
    CHECK (
      status IN ('created', 'updated', 'unchanged', 'rejected', 'duplicate')
    ),
  CONSTRAINT contact_import_rows_reason_valid
    CHECK (
      reason IS NULL
      OR reason IN ('missing_phone', 'invalid_phone', 'duplicate_in_file')
    ),
  CONSTRAINT contact_import_rows_outcome_consistent
    CHECK (
      (
        status IN ('created', 'updated', 'unchanged')
        AND contact_id IS NOT NULL
        AND phone_fingerprint IS NOT NULL
        AND reason IS NULL
      )
      OR
      (
        status = 'duplicate'
        AND phone_fingerprint IS NOT NULL
        AND reason = 'duplicate_in_file'
      )
      OR
      (
        status = 'rejected'
        AND contact_id IS NULL
        AND phone_fingerprint IS NULL
        AND reason IN ('missing_phone', 'invalid_phone')
      )
    ),
  CONSTRAINT contact_import_rows_created_at_milliseconds
    CHECK (created_at = date_trunc('milliseconds', created_at)),
  CONSTRAINT contact_import_rows_job_source_uq
    UNIQUE (tenant_id, job_id, source_row_number)
);

CREATE INDEX contact_import_rows_job_phone_idx
  ON contact_import_rows (tenant_id, job_id, phone_fingerprint);

CREATE INDEX contact_import_rows_tenant_contact_idx
  ON contact_import_rows (tenant_id, contact_id);
