-- PostgreSQL Meta connection, webhook receipt, and encrypted credential state.
-- This migration intentionally contains no seed or demonstration data.

CREATE TABLE meta_connections (
  tenant_id BIGINT PRIMARY KEY,
  business_portfolio_id TEXT NOT NULL,
  waba_id TEXT NOT NULL,
  phone_number_id TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  webhook_subscribed_at TIMESTAMPTZ,
  connected_at TIMESTAMPTZ,
  version INTEGER NOT NULL DEFAULT 1,
  created_at TIMESTAMPTZ NOT NULL
    DEFAULT date_trunc('milliseconds', CURRENT_TIMESTAMP),
  updated_at TIMESTAMPTZ NOT NULL
    DEFAULT date_trunc('milliseconds', CURRENT_TIMESTAMP),
  CONSTRAINT meta_connections_tenant_fk
    FOREIGN KEY (tenant_id)
    REFERENCES tenants (id)
    ON DELETE CASCADE,
  CONSTRAINT meta_connections_business_portfolio_id_valid
    CHECK (
      length(business_portfolio_id) BETWEEN 1 AND 255
      AND business_portfolio_id = btrim(business_portfolio_id)
      AND business_portfolio_id !~ '[[:cntrl:]]'
    ),
  CONSTRAINT meta_connections_waba_id_valid
    CHECK (
      length(waba_id) BETWEEN 1 AND 255
      AND waba_id = btrim(waba_id)
      AND waba_id !~ '[[:cntrl:]]'
    ),
  CONSTRAINT meta_connections_phone_number_id_valid
    CHECK (
      length(phone_number_id) BETWEEN 1 AND 255
      AND phone_number_id = btrim(phone_number_id)
      AND phone_number_id !~ '[[:cntrl:]]'
    ),
  CONSTRAINT meta_connections_status_valid
    CHECK (
      status IN (
        'pending',
        'connected',
        'verification_required',
        'revoked',
        'error',
        'restricted'
      )
    ),
  CONSTRAINT meta_connections_lifecycle_consistent
    CHECK (
      (
        status = 'pending'
        AND webhook_subscribed_at IS NULL
        AND connected_at IS NULL
      )
      OR
      (
        status = 'connected'
        AND webhook_subscribed_at IS NOT NULL
        AND connected_at IS NOT NULL
      )
      OR
      status IN ('verification_required', 'revoked', 'error', 'restricted')
    ),
  CONSTRAINT meta_connections_version_positive
    CHECK (version >= 1),
  CONSTRAINT meta_connections_timestamps_valid
    CHECK (
      created_at = date_trunc('milliseconds', created_at)
      AND updated_at = date_trunc('milliseconds', updated_at)
      AND (
        webhook_subscribed_at IS NULL
        OR webhook_subscribed_at =
          date_trunc('milliseconds', webhook_subscribed_at)
      )
      AND (
        connected_at IS NULL
        OR connected_at = date_trunc('milliseconds', connected_at)
      )
      AND updated_at >= created_at
      AND (
        webhook_subscribed_at IS NULL
        OR webhook_subscribed_at >= created_at
      )
      AND (connected_at IS NULL OR connected_at >= created_at)
    ),
  CONSTRAINT meta_connections_tenant_waba_uq
    UNIQUE (tenant_id, waba_id),
  CONSTRAINT meta_connections_waba_uq
    UNIQUE (waba_id),
  CONSTRAINT meta_connections_phone_number_uq
    UNIQUE (phone_number_id)
);

CREATE INDEX meta_connections_status_idx
  ON meta_connections (status);

CREATE TABLE meta_webhook_receipts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  waba_id TEXT NOT NULL,
  event_key TEXT NOT NULL,
  object_type TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'processing',
  attempt_count INTEGER NOT NULL DEFAULT 1,
  last_error_code TEXT,
  received_at TIMESTAMPTZ NOT NULL
    DEFAULT date_trunc('milliseconds', CURRENT_TIMESTAMP),
  processed_at TIMESTAMPTZ,
  updated_at TIMESTAMPTZ NOT NULL
    DEFAULT date_trunc('milliseconds', CURRENT_TIMESTAMP),
  CONSTRAINT meta_webhook_receipts_connection_fk
    FOREIGN KEY (tenant_id, waba_id)
    REFERENCES meta_connections (tenant_id, waba_id)
    ON DELETE CASCADE,
  CONSTRAINT meta_webhook_receipts_event_key_sha256
    CHECK (event_key ~ '^[0-9a-f]{64}$'),
  CONSTRAINT meta_webhook_receipts_object_type_valid
    CHECK (
      length(object_type) BETWEEN 1 AND 255
      AND object_type = btrim(object_type)
      AND object_type !~ '[[:cntrl:]]'
    ),
  CONSTRAINT meta_webhook_receipts_status_valid
    CHECK (status IN ('processing', 'processed', 'failed')),
  CONSTRAINT meta_webhook_receipts_attempt_count_positive
    CHECK (attempt_count >= 1),
  CONSTRAINT meta_webhook_receipts_last_error_code_valid
    CHECK (
      last_error_code IS NULL
      OR (
        length(last_error_code) BETWEEN 1 AND 100
        AND last_error_code = btrim(last_error_code)
        AND last_error_code !~ '[[:cntrl:]]'
      )
    ),
  CONSTRAINT meta_webhook_receipts_state_consistent
    CHECK (
      (
        status = 'processing'
        AND processed_at IS NULL
        AND last_error_code IS NULL
      )
      OR
      (
        status = 'processed'
        AND processed_at IS NOT NULL
        AND last_error_code IS NULL
      )
      OR
      (
        status = 'failed'
        AND processed_at IS NULL
        AND last_error_code IS NOT NULL
      )
    ),
  CONSTRAINT meta_webhook_receipts_timestamps_valid
    CHECK (
      received_at = date_trunc('milliseconds', received_at)
      AND updated_at = date_trunc('milliseconds', updated_at)
      AND (
        processed_at IS NULL
        OR processed_at = date_trunc('milliseconds', processed_at)
      )
      AND updated_at >= received_at
      AND (processed_at IS NULL OR processed_at >= received_at)
    ),
  CONSTRAINT meta_webhook_receipts_tenant_event_uq
    UNIQUE (tenant_id, event_key)
);

CREATE INDEX meta_webhook_receipts_tenant_status_idx
  ON meta_webhook_receipts (tenant_id, status, updated_at);

CREATE TABLE meta_credential_envelopes (
  tenant_id BIGINT PRIMARY KEY,
  key_version TEXT NOT NULL,
  initialization_vector TEXT NOT NULL,
  ciphertext TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL
    DEFAULT date_trunc('milliseconds', CURRENT_TIMESTAMP),
  updated_at TIMESTAMPTZ NOT NULL
    DEFAULT date_trunc('milliseconds', CURRENT_TIMESTAMP),
  CONSTRAINT meta_credential_envelopes_tenant_fk
    FOREIGN KEY (tenant_id)
    REFERENCES tenants (id)
    ON DELETE CASCADE,
  CONSTRAINT meta_credential_envelopes_key_version_valid
    CHECK (key_version = 'v1'),
  CONSTRAINT meta_credential_envelopes_iv_base64
    CHECK (
      length(initialization_vector) = 16
      AND initialization_vector ~ '^[A-Za-z0-9+/]{16}$'
    ),
  CONSTRAINT meta_credential_envelopes_ciphertext_bounded
    CHECK (
      length(ciphertext) BETWEEN 24 AND 12000
      AND ciphertext ~ '^[A-Za-z0-9+/]+={0,2}$'
    ),
  CONSTRAINT meta_credential_envelopes_timestamps_valid
    CHECK (
      created_at = date_trunc('milliseconds', created_at)
      AND updated_at = date_trunc('milliseconds', updated_at)
      AND updated_at >= created_at
    )
);
