-- PostgreSQL contact-consent evidence and atomic state projection.
-- This migration intentionally contains no seed or demonstration data.

CREATE TABLE contact_consent_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  contact_id BIGINT NOT NULL,
  event_type TEXT NOT NULL,
  source TEXT NOT NULL,
  occurred_at TIMESTAMPTZ NOT NULL,
  evidence_reference TEXT,
  actor_external_user_id TEXT NOT NULL,
  idempotency_key TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  CONSTRAINT contact_consent_events_contact_fk
    FOREIGN KEY (tenant_id, contact_id)
    REFERENCES contacts (tenant_id, id)
    ON DELETE CASCADE,
  CONSTRAINT contact_consent_events_type_valid
    CHECK (event_type IN ('granted', 'unsubscribed')),
  CONSTRAINT contact_consent_events_source_bounded
    CHECK (
      length(source) BETWEEN 1 AND 256
      AND source = btrim(source)
      AND source !~ '[[:cntrl:]]'
    ),
  CONSTRAINT contact_consent_events_evidence_bounded
    CHECK (
      evidence_reference IS NULL
      OR (
        length(evidence_reference) BETWEEN 1 AND 2048
        AND evidence_reference = btrim(evidence_reference)
        AND evidence_reference !~ '[[:cntrl:]]'
      )
    ),
  CONSTRAINT contact_consent_events_actor_bounded
    CHECK (
      length(actor_external_user_id) BETWEEN 1 AND 255
      AND actor_external_user_id = btrim(actor_external_user_id)
      AND actor_external_user_id !~ '[[:cntrl:]]'
    ),
  CONSTRAINT contact_consent_events_key_sha256
    CHECK (idempotency_key ~ '^contact_consent_v1_[0-9a-f]{64}$'),
  CONSTRAINT contact_consent_events_timestamps_milliseconds
    CHECK (
      occurred_at = date_trunc('milliseconds', occurred_at)
      AND created_at = date_trunc('milliseconds', created_at)
    ),
  CONSTRAINT contact_consent_events_tenant_key_uq
    UNIQUE (tenant_id, idempotency_key)
);

CREATE INDEX contact_consent_events_contact_time_idx
  ON contact_consent_events (tenant_id, contact_id, occurred_at, id);

CREATE FUNCTION reject_contact_consent_event_mutation()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  RAISE EXCEPTION 'Contact consent events are immutable';
END;
$$;

CREATE TRIGGER contact_consent_events_update_guard
BEFORE UPDATE ON contact_consent_events
FOR EACH ROW
EXECUTE FUNCTION reject_contact_consent_event_mutation();

CREATE TRIGGER contact_consent_events_delete_guard
BEFORE DELETE ON contact_consent_events
FOR EACH ROW
EXECUTE FUNCTION reject_contact_consent_event_mutation();
