function slice(definition) {
  return Object.freeze({
    ...definition,
    tables: Object.freeze([...definition.tables]),
    requires: Object.freeze([...definition.requires]),
    d1Migrations: Object.freeze([...definition.d1Migrations]),
    postgresMigrations: Object.freeze([...definition.postgresMigrations]),
  });
}

export const POSTGRES_DATA_MIGRATION_SLICES = Object.freeze([
  slice({
    id: "core",
    order: 1,
    status: "rehearsed",
    requires: [],
    tables: [
      "tenants",
      "tenant_memberships",
      "tenant_selections",
      "business_profiles",
      "contacts",
      "contact_consent_events",
      "audit_logs",
    ],
    d1Migrations: [
      "0000_connect_foundation.sql",
      "0001_tenant_provisioning.sql",
      "0002_contacts_and_consent.sql",
      "0021_tenant_selection.sql",
    ],
    postgresMigrations: [
      "0000_core_contacts.sql",
      "0002_tenant_access_foundation.sql",
      "0021_contact_consent_events.sql",
    ],
  }),
  slice({
    id: "tenant-access",
    order: 2,
    status: "rehearsed",
    requires: ["core"],
    tables: [
      "tenant_membership_events",
      "team_invitations",
      "team_invitation_events",
      "team_invitation_deliveries",
      "team_invitation_acceptances",
    ],
    d1Migrations: [
      "0022_tenant_membership_lifecycle.sql",
      "0023_team_invitation_lifecycle.sql",
      "0024_team_invitation_outbox.sql",
      "0025_team_invitation_reconciliation.sql",
      "0026_team_invitation_transition_outbox_guard.sql",
      "0027_team_invitation_system_actor.sql",
      "0028_team_invitation_expiration_scan.sql",
      "0029_team_invitation_acceptance.sql",
    ],
    postgresMigrations: [
      "0003_tenant_membership_events.sql",
      "0004_team_invitation_lifecycle.sql",
    ],
  }),
  slice({
    id: "contact-organization-import",
    order: 3,
    status: "rehearsed",
    requires: ["core"],
    tables: [
      "contact_tags",
      "contact_lists",
      "contact_tag_assignments",
      "contact_list_memberships",
      "contact_import_jobs",
      "contact_import_rows",
    ],
    d1Migrations: [
      "0003_contact_import_jobs.sql",
      "0005_contact_tags_and_lists.sql",
    ],
    postgresMigrations: ["0009_contact_organization_imports.sql"],
  }),
  slice({
    id: "meta-connection",
    order: 4,
    status: "rehearsed",
    requires: ["core"],
    tables: [
      "meta_connections",
      "meta_webhook_receipts",
      "meta_credential_envelopes",
    ],
    d1Migrations: [
      "0006_meta_connection_webhooks.sql",
      "0007_meta_credential_vault.sql",
    ],
    postgresMigrations: ["0010_meta_connection_credentials.sql"],
  }),
  slice({
    id: "templates-campaigns",
    order: 5,
    status: "rehearsed",
    requires: ["core", "contact-organization-import", "meta-connection"],
    tables: [
      "message_templates",
      "campaigns",
      "campaign_recipients",
    ],
    d1Migrations: [
      "0008_message_templates.sql",
      "0009_template_submission_lifecycle.sql",
      "0010_template_status_events.sql",
      "0011_campaign_foundation.sql",
    ],
    postgresMigrations: [
      "0006_message_templates_campaigns.sql",
      "0015_campaign_dispatch.sql",
    ],
  }),
  slice({
    id: "conversations-messages",
    order: 6,
    status: "next",
    requires: ["core", "meta-connection"],
    tables: ["conversations", "messages"],
    d1Migrations: ["0012_conversations_and_messages.sql"],
    postgresMigrations: ["0005_conversations_messages.sql"],
  }),
  slice({
    id: "bot-runtime",
    order: 7,
    status: "planned",
    requires: ["core", "conversations-messages"],
    tables: ["bot_flows", "bot_flow_versions", "bot_reply_deliveries"],
    d1Migrations: [
      "0013_bot_flow_foundation.sql",
      "0014_neat_kingpin.sql",
    ],
    postgresMigrations: ["0007_bot_flows_deliveries.sql"],
  }),
  slice({
    id: "ai-knowledge-runtime",
    order: 8,
    status: "planned",
    requires: ["core", "conversations-messages"],
    tables: [
      "ai_agents",
      "ai_agent_versions",
      "knowledge_sources",
      "knowledge_passages",
      "ai_agent_version_sources",
      "ai_runtime_cost_authorizations",
      "ai_runtime_usage",
      "ai_runtime_audit_events",
      "ai_reply_outbox",
    ],
    d1Migrations: [
      "0015_chilly_dreaming_celestial.sql",
      "0016_uneven_firestar.sql",
      "0017_unusual_veda.sql",
      "0018_material_guardian.sql",
    ],
    postgresMigrations: [
      "0008_ai_reporting.sql",
      "0016_ai_knowledge.sql",
      "0017_ai_reply_outbox.sql",
    ],
  }),
  slice({
    id: "governance-billing",
    order: 9,
    status: "planned",
    requires: ["core"],
    tables: [
      "tenant_subscriptions",
      "tenant_subscription_events",
      "production_decision_records",
      "production_decision_events",
      "business_profile_admin_events",
    ],
    d1Migrations: [
      "0019_purple_silvermane.sql",
      "0020_production_decision_records.sql",
      "0033_large_union_jack.sql",
    ],
    postgresMigrations: [
      "0018_tenant_subscriptions.sql",
      "0019_production_decisions.sql",
      "0020_system_admin_business_profiles.sql",
    ],
  }),
  slice({
    id: "whatsapp-delivery-policy",
    order: 10,
    status: "planned",
    requires: ["core", "meta-connection", "templates-campaigns"],
    tables: [
      "campaign_delivery_provider_links",
      "whatsapp_campaign_delivery_policy_events",
      "whatsapp_rate_limit_reservations",
      "whatsapp_pair_rate_limit_state",
      "whatsapp_portfolio_recipient_rate_limit_state",
      "whatsapp_rate_limit_settlements",
      "whatsapp_provider_cooldown_events",
      "whatsapp_provider_cooldown_state",
    ],
    d1Migrations: [
      "0030_whatsapp_rate_limit_reservations.sql",
      "0031_campaign_delivery_provider_links.sql",
      "0032_whatsapp_provider_cooldowns.sql",
      "0034_whatsapp_campaign_delivery_policy_events.sql",
      "0035_whatsapp_phone_throughput.sql",
    ],
    postgresMigrations: [
      "0011_whatsapp_delivery_policy.sql",
      "0012_whatsapp_rate_limit_ledger.sql",
      "0013_whatsapp_phone_throughput.sql",
      "0022_campaign_delivery_provider_links.sql",
    ],
  }),
]);
