export const hostingMigrationDecisionStates = [
  "selected",
  "decision-required",
] as const;

export type HostingMigrationDecisionState =
  (typeof hostingMigrationDecisionStates)[number];

export const hostingMigrationNextActions = [
  "adapter-required",
  "configuration-required",
  "provider-decision-required",
  "evidence-rebuild-required",
] as const;

export type HostingMigrationNextAction =
  (typeof hostingMigrationNextActions)[number];

export type HostingMigrationTargetProvider =
  | "vercel"
  | "railway"
  | "better-stack"
  | "aws-s3"
  | "vercel+railway"
  | "unknown/unavailable";

export interface HostingMigrationCapability {
  id: string;
  currentBindings: readonly string[];
  currentResources: readonly string[];
  sourceFiles: readonly string[];
  targetPlacement: string;
  targetContract: string;
  targetProvider: HostingMigrationTargetProvider;
  decisionState: HostingMigrationDecisionState;
  nextAction: HostingMigrationNextAction;
  cutoverBlocker: string;
}

function capability(
  definition: HostingMigrationCapability,
): Readonly<HostingMigrationCapability> {
  return Object.freeze({
    ...definition,
    currentBindings: Object.freeze([
      ...definition.currentBindings,
    ]),
    currentResources: Object.freeze([
      ...definition.currentResources,
    ]),
    sourceFiles: Object.freeze([
      ...definition.sourceFiles,
    ]),
  });
}

/**
 * Contract-freeze inventory for ADR-0001.
 *
 * This registry maps the current Cloudflare-specific runtime to the accepted
 * Vercel/Railway direction. It does not select an unapproved database, queue,
 * storage, monitoring, or backup provider and it does not claim migration
 * readiness.
 */
export const HOSTING_MIGRATION_REGISTRY = Object.freeze([
  capability({
    id: "web.build-runtime",
    currentBindings: [],
    currentResources: [
      "vinext",
      "@cloudflare/vite-plugin",
      "sites-vite-plugin",
    ],
    sourceFiles: [
      "vite.config.ts",
      "next.config.ts",
      "package.json",
      "app/layout.tsx",
      "styles/tokens.css",
      "server/platform/vercelUnavailableCloudflareEnvironment.ts",
      ".openai/hosting.json",
    ],
    targetPlacement: "vercel-web",
    targetContract:
      "Vercel-supported React/Next.js build and runtime",
    targetProvider: "vercel",
    decisionState: "selected",
    nextAction: "configuration-required",
    cutoverBlocker:
      "A separate Next.js 16 Webpack production build now passes locally without downloading Google Fonts. The Vercel build replaces the Cloudflare-only virtual environment with a frozen empty binding map, so legacy Cloudflare paths fail closed instead of receiving D1, R2, queue or secret bindings. The default production command still emits a Cloudflare Worker through Vinext; Vercel project configuration, environment values, preview deployment, route smoke evidence and remaining legacy-route migration are still unavailable.",
  }),
  capability({
    id: "web.server-api-boundary",
    currentBindings: [],
    currentResources: [
      "co-located Server Actions and business services",
    ],
    sourceFiles: [
      "app",
      "server",
      "server/platform/railwayApiContract.ts",
      "server/platform/railwayApiClient.ts",
      "server/platform/railwayApiHttpHandler.ts",
      "server/platform/railwayApiIdentityConfiguration.ts",
      "server/platform/railwayApiIdentityAdapters.ts",
      "server/platform/vercelOidcVerifier.ts",
      "server/platform/clerkEndUserSessionVerifier.ts",
      "server/platform/railwayTenantSessionResolver.ts",
      "server/platform/railwayApiOperationRegistry.ts",
      "server/platform/railwayApiMutationExecutor.ts",
      "server/platform/railwayConversationMutationExecutor.ts",
      "server/platform/postgresRailwayConversationMutationExecutor.ts",
      "server/conversations/conversationActions.ts",
      "server/conversations/currentInbox.ts",
      "server/conversations/railwayConversationHandler.ts",
      "server/conversations/currentRailwayConversationHandler.ts",
      "server/conversations/railwayConversationResult.ts",
      "server/bot/currentBotFlows.ts",
      "server/bot/botFlowActions.ts",
      "server/bot/railwayBotFlowHandler.ts",
      "server/bot/currentRailwayBotFlowHandler.ts",
      "server/bot/railwayBotFlowResult.ts",
      "server/platform/railwayBotFlowMutationExecutor.ts",
      "server/platform/postgresRailwayBotFlowMutationExecutor.ts",
      "server/ai/railwayAiReplyApprovalHandler.ts",
      "server/ai/currentRailwayAiReplyApprovalHandler.ts",
      "server/ai/railwayAiReplyApprovalResult.ts",
      "server/platform/railwayAiReplyApprovalMutationExecutor.ts",
      "server/platform/postgresRailwayAiReplyApprovalMutationExecutor.ts",
      "server/onboarding/currentBusinessProfile.ts",
      "server/onboarding/saveBusinessProfileAction.ts",
      "server/onboarding/businessProfileActionResult.ts",
      "server/onboarding/railwayBusinessProfileHandler.ts",
      "server/onboarding/currentRailwayBusinessProfileHandler.ts",
      "server/onboarding/railwayBusinessProfileResult.ts",
      "server/platform/railwayOnboardingBusinessProfileOperations.ts",
      "server/platform/railwayOnboardingBusinessProfileMutationExecutor.ts",
      "server/platform/postgresRailwayOnboardingBusinessProfileMutationExecutor.ts",
      "server/platform/postgresClerkOrganizationBindingRepository.ts",
      "shared/domain/businessProfileView.ts",
      "server/auth/tenantSelectionActions.ts",
      "server/auth/tenantSelectionActionResult.ts",
      "server/auth/railwayTenantSelectionHandler.ts",
      "server/auth/currentRailwayTenantSelectionHandler.ts",
      "server/auth/railwayTenantSelectionResult.ts",
      "server/platform/railwayTenantSelectionOperations.ts",
      "server/platform/railwayTenantSelectionMutationExecutor.ts",
      "server/platform/postgresRailwayTenantSelectionMutationExecutor.ts",
      "server/team/currentTeamDirectory.ts",
      "server/team/railwayTeamDirectoryHandler.ts",
      "server/team/currentRailwayTeamDirectoryHandler.ts",
      "server/team/railwayTeamDirectoryResult.ts",
      "server/platform/railwayTeamDirectoryOperation.ts",
      "server/team/teamMembershipActions.ts",
      "server/team/railwayTeamMembershipHandler.ts",
      "server/team/currentRailwayTeamMembershipHandler.ts",
      "server/team/railwayTeamMembershipResult.ts",
      "server/platform/railwayTeamMembershipOperations.ts",
      "server/team/teamInvitationActions.ts",
      "server/team/railwayTeamInvitationRequestHandler.ts",
      "server/team/currentRailwayTeamInvitationRequestHandler.ts",
      "server/team/railwayTeamInvitationRequestResult.ts",
      "server/platform/railwayTeamInvitationRequestOperation.ts",
      "server/team/teamInvitationAcceptanceActions.ts",
      "server/team/teamInvitationAcceptanceIdentityResolver.ts",
      "server/team/railwayTeamInvitationAcceptanceHandler.ts",
      "server/team/currentRailwayTeamInvitationAcceptanceHandler.ts",
      "server/team/railwayTeamInvitationAcceptanceResult.ts",
      "server/platform/clerkRailwayTeamInvitationIdentityResolver.ts",
      "server/platform/clerkRailwayTeamInvitationProvider.ts",
      "server/platform/railwayTeamInvitationAcceptanceOperation.ts",
      "server/campaigns/railwayCampaignHandler.ts",
      "server/campaigns/currentRailwayCampaignHandler.ts",
      "server/campaigns/railwayCampaignResult.ts",
      "server/platform/railwayCampaignMutationExecutor.ts",
      "server/platform/postgresRailwayCampaignMutationExecutor.ts",
      "server/platform/railwayContactImportMutationExecutor.ts",
      "server/platform/postgresRailwayContactImportMutationExecutor.ts",
      "server/contacts/railwayContactImportHandler.ts",
      "server/contacts/currentRailwayContactImportHandler.ts",
      "server/platform/railwayMessageTemplateDraftMutationExecutor.ts",
      "server/platform/postgresRailwayMessageTemplateDraftMutationExecutor.ts",
      "server/platform/railwayMessageTemplateSubmissionMutationExecutor.ts",
      "server/platform/postgresRailwayMessageTemplateSubmissionMutationExecutor.ts",
      "server/platform/railwayMessageTemplateProviderRuntime.ts",
      "server/platform/railwayMessageTemplateSubmissionWorkerRuntime.ts",
      "server/platform/railwayMessageTemplateSubmissionReconciliationRuntime.ts",
      "server/platform/railwayMessageTemplateSubmissionMaintenanceRuntime.ts",
      "server/templates/railwayMessageTemplateDirectoryHandler.ts",
      "server/templates/currentRailwayMessageTemplateDirectoryHandler.ts",
      "server/templates/railwayMessageTemplateDraftHandler.ts",
      "server/templates/currentRailwayMessageTemplateDraftHandler.ts",
      "server/templates/railwayMessageTemplateSubmissionHandler.ts",
      "server/templates/currentRailwayMessageTemplateSubmissionHandler.ts",
      "server/templates/messageTemplateSubmissionOutbox.ts",
      "server/templates/messageTemplateSubmissionWorker.ts",
      "server/templates/messageTemplateSubmissionReconciliation.ts",
      "server/templates/messageTemplateSubmissionMaintenanceRunner.ts",
      "server/platform/postgresTransaction.ts",
      "server/platform/nodePostgresAdapter.ts",
      "server/platform/nodePostgresPoolConfiguration.ts",
      "server/platform/postgresReadinessProbe.ts",
      "server/platform/railwayPostgresFoundation.ts",
      "server/platform/railwayPostgresApiRuntime.ts",
      "server/platform/railwayMetaWebhookRuntime.ts",
      "server/platform/railwayNodeHttpServer.ts",
      "server/platform/railwayNodeProcess.ts",
      "server/platform/railwayNodeService.ts",
      "server/platform/postgresResultValidation.ts",
      "server/platform/postgresTenantMembershipRepository.ts",
      "server/platform/postgresTenantMembershipMutationRepository.ts",
      "server/platform/postgresTenantSelectionRepository.ts",
      "server/platform/postgresRailwayApiMutationExecutor.ts",
      "server/platform/postgresTeamInvitationRepository.ts",
      "server/platform/postgresTeamInvitationExpirationRepository.ts",
      "server/platform/postgresTeamInvitationDeliveryRepository.ts",
      "server/platform/clerkRailwayTeamInvitationProvider.ts",
      "server/platform/postgresTeamInvitationAcceptanceRepository.ts",
      "server/platform/postgresContactReadRepository.ts",
      "server/platform/postgresContactConsentRepository.ts",
      "server/platform/postgresConversationRepository.ts",
      "server/platform/railwayConversationMutationExecutor.ts",
      "server/platform/postgresRailwayConversationMutationExecutor.ts",
      "server/platform/postgresBotFlowRepository.ts",
      "server/platform/postgresRailwayBotFlowMutationExecutor.ts",
      "server/platform/postgresBotReplyDeliveryRepository.ts",
      "server/platform/postgresBotReplyDeliveryProviderRepository.ts",
      "server/operations/botReplyStagingLiveDriver.ts",
      "server/operations/botReplyStagingDurableRunner.ts",
      "server/operations/botReplyStagingQueueMessage.ts",
      "server/operations/botReplyStagingQueueConsumer.ts",
      "server/operations/botReplyStagingQueuedExecutor.ts",
      "server/operations/botReplyStagingScenarioExecutor.ts",
      "server/operations/botReplyStagingProviderDriver.ts",
      "server/operations/botReplyStagingProviderCaseInventory.ts",
      "server/operations/botReplyStagingPrivateCaseSource.ts",
      "server/operations/botReplyStagingObservationSource.ts",
      "server/meta/metaGraphBotReplyStagingObservationReader.ts",
      "server/platform/railwayBotReplyStagingSecurityObservationReader.ts",
      "server/platform/railwayBotReplyStagingKillSwitch.ts",
      "server/operations/botReplyStagingRecipientFingerprint.ts",
      "server/platform/railwayBullMqBotReplyStagingQueue.ts",
      "server/platform/railwayBotReplyStagingProviderDriverFactory.ts",
      "server/platform/railwayBotReplyStagingActivationPreflight.ts",
      "server/platform/railwayBotReplyStagingApiConfiguration.ts",
      "server/platform/railwayBotReplyStagingCrossServiceActivation.ts",
      "server/platform/railwayBotReplyStagingCrossServiceEvidence.ts",
      "server/platform/railwayBotReplyStagingReleaseEvidenceIssuer.ts",
      "server/platform/railwayBotReplyStagingReleaseEvidencePublisher.ts",
      "server/platform/railwayBotReplyStagingReleaseEvidenceStorageConfiguration.ts",
      "server/platform/postgresBotReplyStagingReleaseEvidenceRepository.ts",
      "server/platform/railwayBullMqPostgresApiRuntime.ts",
      "server/platform/railwayBullMqApiMain.ts",
      "server/platform/railwaySystemAdminBotReplyStagingOperation.ts",
      "server/platform/railwaySystemAdminBotReplyStagingAuthorizationOperation.ts",
      "server/platform/postgresBotReplyStagingRunRepository.ts",
      "server/platform/postgresBotReplyStagingSafetyRepository.ts",
      "server/platform/postgresBotReplyStagingServiceWindowSource.ts",
      "server/platform/postgresBotReplyStagingDurableObservationReader.ts",
      "server/platform/postgresBotReplyStagingDurableObservationWriter.ts",
      "server/platform/postgresBotReplyStagingWebhookObservationProducer.ts",
      "server/platform/postgresBotReplyStagingProviderDeferralObservationProducer.ts",
      "server/platform/postgresBotReplyStagingSendObservationProducer.ts",
      "server/platform/postgresBotRuntimeRepository.ts",
      "server/platform/postgresTenantSubscriptionRepository.ts",
      "server/platform/postgresTenantProvisioningRepository.ts",
      "server/platform/postgresProductionDecisionRepository.ts",
      "server/platform/postgresSystemAdminBusinessProfileRepository.ts",
      "server/platform/postgresSystemAdminTenantDirectoryRepository.ts",
      "server/platform/postgresKnowledgeSourceRepository.ts",
      "server/platform/postgresKnowledgePassageRepository.ts",
      "server/platform/postgresAiAgentRepository.ts",
      "server/platform/postgresAiReplyOutboxRepository.ts",
      "server/platform/postgresRailwayAiReplyApprovalMutationExecutor.ts",
      "server/platform/postgresRailwayOnboardingBusinessProfileMutationExecutor.ts",
      "server/platform/postgresAiRuntimeRepository.ts",
      "server/platform/postgresContactOrganizationRepository.ts",
      "server/platform/postgresContactImportRepository.ts",
      "server/platform/postgresMetaRepository.ts",
      "server/platform/postgresMetaCredentialRepository.ts",
      "server/platform/postgresWhatsappCampaignDeliveryPolicyRepository.ts",
      "server/platform/postgresWhatsappRateLimitRepository.ts",
      "server/platform/postgresWorkerSchedulerLeaseRepository.ts",
      "server/platform/postgresCampaignAudienceRepository.ts",
      "server/platform/postgresCampaignDispatchRepository.ts",
      "server/platform/postgresCampaignDeliveryProviderRepository.ts",
      "server/platform/postgresCampaignRepository.ts",
      "server/platform/postgresRailwayCampaignMutationExecutor.ts",
      "server/platform/postgresMessageTemplateRepository.ts",
      "server/platform/postgresMessageTemplateSubmissionOutboxRepository.ts",
      "server/platform/postgresOperationalReportRepository.ts",
      "postgres/migrations/0004_team_invitation_lifecycle.sql",
      "postgres/migrations/0005_conversations_messages.sql",
      "postgres/migrations/0006_message_templates_campaigns.sql",
      "postgres/migrations/0007_bot_flows_deliveries.sql",
      "postgres/migrations/0008_ai_reporting.sql",
      "postgres/migrations/0009_contact_organization_imports.sql",
      "postgres/migrations/0010_meta_connection_credentials.sql",
      "postgres/migrations/0011_whatsapp_delivery_policy.sql",
      "postgres/migrations/0012_whatsapp_rate_limit_ledger.sql",
      "postgres/migrations/0013_whatsapp_phone_throughput.sql",
      "postgres/migrations/0014_worker_scheduler_lease.sql",
      "postgres/migrations/0015_campaign_dispatch.sql",
      "postgres/migrations/0016_ai_knowledge.sql",
      "postgres/migrations/0017_ai_reply_outbox.sql",
      "postgres/migrations/0018_tenant_subscriptions.sql",
      "postgres/migrations/0019_production_decisions.sql",
      "postgres/migrations/0020_system_admin_business_profiles.sql",
      "postgres/migrations/0021_contact_consent_events.sql",
      "postgres/migrations/0022_campaign_delivery_provider_links.sql",
      "postgres/migrations/0023_api_mutation_rate_limits.sql",
      "postgres/migrations/0024_whatsapp_legacy_reservation_category.sql",
      "postgres/migrations/0025_data_migration_bundle_receipts.sql",
      "postgres/migrations/0026_message_template_submission_outbox.sql",
      "postgres/migrations/0027_clerk_organization_binding.sql",
      "postgres/migrations/0028_clerk_invitation_rate_limit.sql",
      "postgres/migrations/0029_team_invitation_delivery_deferrals.sql",
      "postgres/migrations/0030_whatsapp_service_reply_reservations.sql",
      "postgres/migrations/0031_bot_reply_delivery_deferrals.sql",
      "postgres/migrations/0032_bot_reply_delivery_provider_links.sql",
      "postgres/migrations/0033_bot_reply_staging_runs.sql",
      "postgres/migrations/0034_bot_reply_staging_authorizations.sql",
      "postgres/migrations/0035_bot_reply_staging_observations.sql",
      "postgres/migrations/0036_bot_reply_provider_attempt_provenance.sql",
      "postgres/migrations/0037_inbound_button_reply_provenance.sql",
      "postgres/migrations/0038_bot_reply_service_window_rejection_provenance.sql",
      "postgres/migrations/0039_bot_reply_provider_request_fence.sql",
      "postgres/migrations/0040_bot_reply_staging_release_evidence.sql",
      "postgres/migrations/0041_production_readiness_release_evidence_v2.sql",
      "postgres/migrations/0042_bot_reply_provider_outcome_request_fence.sql",
      "postgres/migrations/0043_bot_reply_staging_release_evidence_operator_audit.sql",
      "postgres/migrations/0044_bot_reply_staging_release_evidence_atomic_publish.sql",
      "postgres/migrations/0045_bot_reply_provider_clock_domains.sql",
      "postgres/migrations/0046_bot_reply_staging_release_evidence_atomic_initialize.sql",
      "postgres/migrations/0047_bot_reply_staging_attestation_nonce_ledger.sql",
      "postgres/migrations/0048_bot_reply_staging_attested_evidence_atomic_publish.sql",
      "postgres/migrations/0049_bot_reply_staging_attested_evidence_readback.sql",
      "postgres/migrations/0050_bot_reply_staging_trigger_hardening.sql",
      "postgres/migrations/0051_bot_reply_staging_run_capability_wrappers.sql",
      "postgres/migrations/0052_bot_reply_staging_authorization_observation_hardening.sql",
      "postgres/migrations/0053_bot_reply_staging_provider_operation_fence.sql",
      "postgres/migrations/0054_meta_credential_revision_ledger.sql",
      "postgres/migrations/0055_bot_reply_staging_credential_bound_pre_send_permit.sql",
      "postgres/migrations/0056_bot_reply_staging_credential_bound_pre_send_session_barrier.sql",
      "postgres/migrations/0057_bot_reply_staging_writer_barrier_and_late_truth.sql",
      "postgres/postgresMigrationParityRegistry.mjs",
      "scripts/read-d1-full-data-migration-snapshot.mjs",
      "scripts/run-postgres-full-data-migration-cutover.mjs",
      "scripts/verify-d1-full-data-migration-snapshot.mjs",
      "scripts/verify-postgres-migration-parity.mjs",
      "server/platform/postgresDataMigrationBundleProtocol.ts",
      "server/platform/postgresFullDataMigrationBundle.ts",
      "server/platform/postgresFullDataMigrationCutover.ts",
      "server/platform/postgresMutationRateLimitBinding.ts",
      "server/platform/postgresMutationRateLimitConfiguration.ts",
      "server/platform/railwayApiRuntime.ts",
      "worker/index.ts",
    ],
    targetPlacement: "vercel-web+railway-api",
    targetContract:
      "Versioned authenticated HTTP API with bounded DTOs",
    targetProvider: "vercel+railway",
    decisionState: "selected",
    nextAction: "adapter-required",
    cutoverBlocker:
      "The authenticated runtime, initial reads, guarded contacts.save mutation, provider-neutral PostgreSQL transaction executor, node-postgres transaction adapter, pool contract, PostgreSQL contacts.list read, a full grant/unsubscribe Vercel BFF over immutable contact-consent evidence with atomic latest-event projection, four contact-organization mutations, contact-import start/chunk mutations, a complete onboarding business-profile read/save Vercel BFF with atomic first-owner provisioning, receipt and audit, a complete tenant-selection directory/save Vercel BFF with opaque identifiers, atomic receipt and audit, a complete team-directory, membership-mutation, invitation-request, and invitation-acceptance Vercel BFF with opaque references, immutable events and server-resolved verified primary email, a complete conversation list/thread/mark-read/assignment Vercel BFF with atomic receipts and audit, complete bot-flow list/details/draft/publish routes without D1 fallback and with atomic receipts and audit, a complete campaign directory/snapshot/activation Vercel BFF, a complete AI-agent directory/details/draft/publish Vercel BFF, and complete AI reply approval list/decide routes without D1 fallback and with atomic receipts and audit, message-template list/draft save with atomic receipts, audit, replay snapshots and no D1 fallback, plus a fail-closed Railway Meta template provider runtime over PostgreSQL encrypted credential envelopes and an atomic template submission outbox with immutable transition evidence, a single-POST worker, bounded relay and GET-only reconciliation exist; tenant-isolated campaign-audience reads, atomic contact-import, conversation/message inbox persistence, bot-flow version/publication, reply-delivery and bot-runtime continuation/handoff persistence, knowledge-source lifecycle and atomic knowledge-passage persistence, AI-agent draft/version/source-link/publication persistence, serialized AI-runtime cost authorization/usage plus audited handoff persistence, AI reply approval-outbox persistence and a complete approval list/decide API bridge, tenant-subscription lifecycle persistence with immutable audit events, first-owner tenant provisioning with identity-conflict protection, an authoritative Clerk Organization binding with fail-closed tenant isolation, registered production-decision persistence with immutable audit evidence, bounded system-admin tenant directory and audited profile updates, Meta connection/webhook and encrypted credential paths, immutable WhatsApp delivery-policy evidence and kill switch, serialized WhatsApp reservation/settlement/provider-cooldown ledger, provider-bound rolling phone-throughput enforcement, fenced worker-scheduler lease, message-template lifecycle, campaign-snapshot, campaign-dispatch and atomic provider-reconciliation persistence, single-statement reports.read adapter, fifty-four-adapter PostgreSQL foundation, owned PostgreSQL API runtime composition, shared PostgreSQL token-bucket contracts for tenant mutations, system-admin mutations, Meta webhook ingress and Clerk Organization invitation creation, bounded Node HTTP adapter, database readiness probe, ordered HTTP-before-pool shutdown owner, strict PORT configuration, SIGINT/SIGTERM lifecycle, and an executable API bootstrap also exist. All six operational-report source families are migrated, the complete authenticated reports.read HTTP path passed against PostgreSQL 16.13, and a deterministic registry maps all 43 D1 migrations and all 55 D1 tables to the 58 PostgreSQL migrations. Local rehearsals prove data migration and semantic parity for all ten slices and all 55 tables through migration 0034, including durable Clerk Retry-After deferrals and bot provider settlement. A read-only single-transaction full-source snapshot boundary validates the exact 55-table D1 export contract without exposing its path or rows. A signed all-slice bundle executes the ten plans atomically and writes an immutable source-level replay receipt. A two-phase operator cutover requires an approved source digest and explicit confirmation before target access; its empty-source rehearsal and graceful SIGTERM shutdown passed against PostgreSQL 16.13. Cutover remains blocked by live Clerk team-invitation execution evidence and production telemetry sinks, live Clerk Organization/MFA/invitation evidence, live Railway service configuration and remaining route wiring, provider-bound pool and rate-limit policy values, a live controlled-environment export and signed full rehearsal, remaining domain mutations, live account configuration, and staging evidence.",
  }),
  capability({
    id: "web.static-assets",
    currentBindings: ["ASSETS"],
    currentResources: ["Cloudflare asset fetcher"],
    sourceFiles: ["worker/index.ts"],
    targetPlacement: "vercel-web",
    targetContract: "Static asset delivery",
    targetProvider: "vercel",
    decisionState: "selected",
    nextAction: "configuration-required",
    cutoverBlocker:
      "Asset delivery is still wired through the Worker ASSETS binding.",
  }),
  capability({
    id: "web.image-optimization",
    currentBindings: ["IMAGES"],
    currentResources: ["Cloudflare image transformation"],
    sourceFiles: ["worker/index.ts"],
    targetPlacement: "vercel-web",
    targetContract: "Bounded image optimization",
    targetProvider: "vercel",
    decisionState: "selected",
    nextAction: "adapter-required",
    cutoverBlocker:
      "The image route still invokes the Cloudflare IMAGES binding.",
  }),
  capability({
    id: "api.meta-webhook-ingress",
    currentBindings: [],
    currentResources: ["Worker fetch route /webhooks/meta"],
    sourceFiles: [
      "worker/index.ts",
      "server/meta/metaWebhookQueuePort.ts",
      "server/meta/metaWebhookQueuePublisher.ts",
      "server/meta/metaWebhookQueueRuntime.ts",
      "server/platform/railwayMetaWebhookRuntime.ts",
      "server/platform/railwayPostgresApiRuntime.ts",
      "server/platform/railwayBullMqMetaWebhookQueue.ts",
      "server/platform/railwayBullMqPostgresApiRuntime.ts",
      "server/platform/railwayBullMqApiMain.ts",
      "server/platform/railwayBetterStackTelemetry.ts",
      "scripts/start-railway-bullmq-api.mjs",
      "docs/better-stack-opentelemetry.md",
      "server/platform/railwayNodeHttpServer.ts",
    ],
    targetPlacement: "railway-api",
    targetContract:
      "Signed bounded Meta webhook ingress",
    targetProvider: "railway",
    decisionState: "selected",
    nextAction: "configuration-required",
    cutoverBlocker:
      "A signed, bounded Railway Node route now composes PostgreSQL connection lookup, an isolated shared Meta-webhook token bucket and a provider-neutral durable queue port. The BullMQ provider composition proves Redis readiness before opening HTTP, returns a bounded failure when publication is unavailable, and has an explicit package start command. Batched Better Stack OTLP Logs with structural redaction and flush-on-shutdown are implemented locally. Live secrets and policy values, a live Better Stack source and ingestion proof, load evidence and current-release Railway staging proof are still unavailable.",
  }),
  capability({
    id: "data.relational-database",
    currentBindings: ["DB"],
    currentResources: ["Cloudflare D1", "43 SQL migrations"],
    sourceFiles: [
      "db",
      "drizzle.config.ts",
      "server/platform/postgresTransaction.ts",
      "server/platform/postgresRailwayApiMutationExecutor.ts",
      "server/platform/postgresResultValidation.ts",
      "server/platform/postgresTenantMembershipRepository.ts",
      "server/platform/postgresTenantMembershipMutationRepository.ts",
      "server/platform/postgresTenantSelectionRepository.ts",
      "server/platform/postgresRailwayTenantSelectionMutationExecutor.ts",
      "server/platform/postgresBusinessProfileRepository.ts",
      "server/platform/postgresTeamInvitationRepository.ts",
      "server/platform/postgresTeamInvitationExpirationRepository.ts",
      "server/platform/postgresTeamInvitationDeliveryRepository.ts",
      "server/platform/postgresTeamInvitationAcceptanceRepository.ts",
      "server/platform/postgresContactReadRepository.ts",
      "server/platform/postgresContactConsentRepository.ts",
      "server/platform/postgresConversationRepository.ts",
      "server/platform/postgresBotFlowRepository.ts",
      "server/platform/postgresRailwayBotFlowMutationExecutor.ts",
      "server/platform/postgresBotReplyDeliveryRepository.ts",
      "server/platform/postgresBotReplyDeliveryProviderRepository.ts",
      "server/operations/botReplyStagingLiveDriver.ts",
      "server/operations/botReplyStagingDurableRunner.ts",
      "server/operations/botReplyStagingScenarioExecutor.ts",
      "server/operations/botReplyStagingProviderDriver.ts",
      "server/operations/botReplyStagingProviderCaseInventory.ts",
      "server/operations/botReplyStagingPrivateCaseSource.ts",
      "server/operations/botReplyStagingObservationSource.ts",
      "server/meta/metaGraphBotReplyStagingObservationReader.ts",
      "server/platform/railwayBotReplyStagingSecurityObservationReader.ts",
      "server/platform/railwayBotReplyStagingKillSwitch.ts",
      "server/operations/botReplyStagingRecipientFingerprint.ts",
      "server/platform/railwayBotReplyStagingProviderDriverFactory.ts",
      "server/platform/railwayBotReplyStagingActivationPreflight.ts",
      "server/platform/railwaySystemAdminBotReplyStagingOperation.ts",
      "server/platform/railwaySystemAdminBotReplyStagingAuthorizationOperation.ts",
      "server/platform/postgresBotReplyStagingRunRepository.ts",
      "server/platform/postgresBotReplyStagingSafetyRepository.ts",
      "server/platform/postgresBotReplyStagingServiceWindowSource.ts",
      "server/platform/postgresBotReplyStagingDurableObservationReader.ts",
      "server/platform/postgresBotReplyStagingDurableObservationWriter.ts",
      "server/platform/postgresBotReplyStagingWebhookObservationProducer.ts",
      "server/platform/postgresBotReplyStagingProviderDeferralObservationProducer.ts",
      "server/platform/postgresBotReplyStagingSendObservationProducer.ts",
      "server/platform/postgresBotRuntimeRepository.ts",
      "server/platform/postgresTenantSubscriptionRepository.ts",
      "server/platform/postgresTenantProvisioningRepository.ts",
      "server/platform/postgresProductionDecisionRepository.ts",
      "server/platform/postgresKnowledgeSourceRepository.ts",
      "server/platform/postgresKnowledgePassageRepository.ts",
      "server/platform/postgresAiAgentRepository.ts",
      "server/platform/postgresAiReplyOutboxRepository.ts",
      "server/platform/postgresRailwayAiReplyApprovalMutationExecutor.ts",
      "server/platform/postgresAiRuntimeRepository.ts",
      "server/platform/postgresContactOrganizationRepository.ts",
      "server/platform/postgresContactImportRepository.ts",
      "server/platform/postgresRailwayContactImportMutationExecutor.ts",
      "server/platform/postgresRailwayMessageTemplateDraftMutationExecutor.ts",
      "server/platform/postgresMetaRepository.ts",
      "server/platform/postgresMetaCredentialRepository.ts",
      "server/platform/postgresWhatsappCampaignDeliveryPolicyRepository.ts",
      "server/platform/postgresWhatsappRateLimitRepository.ts",
      "server/platform/postgresWorkerSchedulerLeaseRepository.ts",
      "server/platform/postgresCampaignAudienceRepository.ts",
      "server/platform/postgresCampaignDispatchRepository.ts",
      "server/platform/postgresCampaignDeliveryProviderRepository.ts",
      "server/platform/postgresCampaignRepository.ts",
      "server/platform/postgresRailwayCampaignMutationExecutor.ts",
      "server/platform/postgresMessageTemplateRepository.ts",
      "server/platform/postgresMessageTemplateSubmissionOutboxRepository.ts",
      "server/platform/postgresOperationalReportRepository.ts",
      "server/platform/postgresSystemAdminBusinessProfileRepository.ts",
      "server/platform/postgresSystemAdminTenantDirectoryRepository.ts",
      "server/platform/postgresReadinessProbe.ts",
      "server/platform/railwayPostgresApiRuntime.ts",
      "postgres/migrations/0000_core_contacts.sql",
      "postgres/migrations/0001_railway_api_mutation_receipts.sql",
      "postgres/migrations/0002_tenant_access_foundation.sql",
      "postgres/migrations/0003_tenant_membership_events.sql",
      "postgres/migrations/0004_team_invitation_lifecycle.sql",
      "postgres/migrations/0005_conversations_messages.sql",
      "postgres/migrations/0006_message_templates_campaigns.sql",
      "postgres/migrations/0007_bot_flows_deliveries.sql",
      "postgres/migrations/0008_ai_reporting.sql",
      "postgres/migrations/0009_contact_organization_imports.sql",
      "postgres/migrations/0010_meta_connection_credentials.sql",
      "postgres/migrations/0011_whatsapp_delivery_policy.sql",
      "postgres/migrations/0012_whatsapp_rate_limit_ledger.sql",
      "postgres/migrations/0013_whatsapp_phone_throughput.sql",
      "postgres/migrations/0014_worker_scheduler_lease.sql",
      "postgres/migrations/0015_campaign_dispatch.sql",
      "postgres/migrations/0016_ai_knowledge.sql",
      "postgres/migrations/0017_ai_reply_outbox.sql",
      "postgres/migrations/0018_tenant_subscriptions.sql",
      "postgres/migrations/0019_production_decisions.sql",
      "postgres/migrations/0020_system_admin_business_profiles.sql",
      "postgres/migrations/0021_contact_consent_events.sql",
      "postgres/migrations/0022_campaign_delivery_provider_links.sql",
      "postgres/migrations/0023_api_mutation_rate_limits.sql",
      "postgres/migrations/0024_whatsapp_legacy_reservation_category.sql",
      "postgres/migrations/0025_data_migration_bundle_receipts.sql",
      "postgres/migrations/0026_message_template_submission_outbox.sql",
      "postgres/migrations/0027_clerk_organization_binding.sql",
      "postgres/migrations/0028_clerk_invitation_rate_limit.sql",
      "postgres/migrations/0029_team_invitation_delivery_deferrals.sql",
      "postgres/migrations/0030_whatsapp_service_reply_reservations.sql",
      "postgres/migrations/0031_bot_reply_delivery_deferrals.sql",
      "postgres/migrations/0032_bot_reply_delivery_provider_links.sql",
      "postgres/migrations/0033_bot_reply_staging_runs.sql",
      "postgres/migrations/0034_bot_reply_staging_authorizations.sql",
      "postgres/migrations/0035_bot_reply_staging_observations.sql",
      "postgres/migrations/0036_bot_reply_provider_attempt_provenance.sql",
      "postgres/migrations/0037_inbound_button_reply_provenance.sql",
      "postgres/migrations/0038_bot_reply_service_window_rejection_provenance.sql",
      "postgres/migrations/0039_bot_reply_provider_request_fence.sql",
      "postgres/migrations/0040_bot_reply_staging_release_evidence.sql",
      "postgres/migrations/0041_production_readiness_release_evidence_v2.sql",
      "postgres/migrations/0042_bot_reply_provider_outcome_request_fence.sql",
      "postgres/migrations/0043_bot_reply_staging_release_evidence_operator_audit.sql",
      "postgres/migrations/0044_bot_reply_staging_release_evidence_atomic_publish.sql",
      "postgres/migrations/0045_bot_reply_provider_clock_domains.sql",
      "postgres/migrations/0046_bot_reply_staging_release_evidence_atomic_initialize.sql",
      "postgres/migrations/0047_bot_reply_staging_attestation_nonce_ledger.sql",
      "postgres/migrations/0048_bot_reply_staging_attested_evidence_atomic_publish.sql",
      "postgres/migrations/0049_bot_reply_staging_attested_evidence_readback.sql",
      "postgres/migrations/0050_bot_reply_staging_trigger_hardening.sql",
      "postgres/migrations/0051_bot_reply_staging_run_capability_wrappers.sql",
      "postgres/migrations/0052_bot_reply_staging_authorization_observation_hardening.sql",
      "postgres/migrations/0053_bot_reply_staging_provider_operation_fence.sql",
      "postgres/migrations/0054_meta_credential_revision_ledger.sql",
      "postgres/migrations/0055_bot_reply_staging_credential_bound_pre_send_permit.sql",
      "postgres/migrations/0056_bot_reply_staging_credential_bound_pre_send_session_barrier.sql",
      "postgres/migrations/0057_bot_reply_staging_writer_barrier_and_late_truth.sql",
      "postgres/postgresMigrationParityRegistry.mjs",
      "postgres/postgresDataMigrationSliceRegistry.mjs",
      "scripts/read-d1-full-data-migration-snapshot.mjs",
      "scripts/run-postgres-full-data-migration-cutover.mjs",
      "scripts/verify-d1-full-data-migration-snapshot.mjs",
      "scripts/verify-postgres-migration-contract.mjs",
      "scripts/verify-postgres-migration-parity.mjs",
      "scripts/verify-node-postgres-integration.mjs",
      "scripts/verify-bot-reply-staging-credential-bound-pre-send-session-barrier-postgres.mjs",
      "docs/postgresql-runtime-role-decision.md",
      "scripts/verify-postgres-core-data-migration.mjs",
      "scripts/verify-postgres-core-semantic-parity.mjs",
      "server/platform/postgresDataMigrationBundleProtocol.ts",
      "server/platform/postgresFullDataMigrationBundle.ts",
      "server/platform/postgresFullDataMigrationCutover.ts",
      "server/platform/postgresMutationRateLimitBinding.ts",
      "server/platform/postgresMutationRateLimitConfiguration.ts",
      "server/platform/postgresRuntimeCapabilityConfiguration.ts",
      "server/platform/postgresRuntimeCapabilityEvidence.ts",
      "server/platform/postgresRuntimeCapabilityTrustedDriverContract.ts",
    ],
    targetPlacement: "shared-managed-service",
    targetContract:
      "Railway PostgreSQL for the controlled Pilot with transactional and concurrency parity",
    targetProvider: "railway",
    decisionState: "selected",
    nextAction: "configuration-required",
    cutoverBlocker:
      "Railway PostgreSQL is selected for the controlled Pilot. Provider-neutral contacts.save, contacts.list, immutable contact-consent evidence with atomic latest-event projection, tenant-isolated campaign-audience reads, contact organization, atomic contact import with API receipts and audit, atomic onboarding business-profile read/save with first-owner provisioning and replay evidence, a complete tenant-selection directory/save API bridge with opaque identifiers, atomic receipts and audit, a complete team-directory, membership-mutation, invitation-request and invitation-acceptance API bridge with opaque identifiers and immutable events, a complete conversation list/thread/mark-read/assignment API bridge with atomic receipts and audit, conversation/message inbox persistence, bot-flow version/publication plus complete list/details/draft/publish API routes with atomic receipts and audit, reply-delivery and bot-runtime continuation/handoff persistence, knowledge-source lifecycle and atomic knowledge-passage persistence, AI-agent draft/version/source-link/publication persistence plus a complete directory/details/draft/publish API bridge with atomic receipts and audit, serialized AI-runtime cost authorization/usage plus audited handoff persistence, AI reply approval-outbox persistence and a complete list/decide API bridge, tenant-subscription lifecycle persistence with immutable audit events, first-owner tenant provisioning with identity-conflict protection, authoritative Clerk Organization binding, registered production-decision persistence with immutable audit evidence, bounded system-admin tenant-directory reads and audited profile-update persistence, Meta connection/webhook and encrypted credential persistence, immutable WhatsApp delivery-policy evidence and kill switch, serialized WhatsApp reservation/settlement/provider-cooldown persistence, provider-bound rolling phone-throughput enforcement, fenced worker-scheduler lease, message-template list/draft API bridge, atomic lifecycle and submission outbox with immutable transition evidence, a complete campaign directory/snapshot/activation API bridge with atomic receipts and audit, campaign-snapshot, campaign-dispatch and atomic provider-reconciliation persistence, shared isolated tenant-mutation, system-admin-mutation and Meta-webhook token buckets plus a dedicated Clerk Organization invitation creation bucket, single-statement reports.read, tenant access, team membership mutation, a complete membership API bridge, and complete invitation lifecycle repositories plus fifty-eight ordered PostgreSQL migrations exist. A deterministic source-parity registry maps all 43 D1 migrations and all 55 D1 tables to those migrations, while separately identifying twenty-nine Railway-only migrations. A read-only single-transaction full-source snapshot boundary validates all ten slices, all 55 source schemas, integrity and foreign keys without printing the export path or rows. A signed all-slice bundle verifies every child plan before opening a target transaction, acquires the existing slice locks in order, executes all ten slices atomically, and persists an immutable receipt unique by bundle and source digest. A two-phase operator cutover keeps payload in memory, requires the reviewed source digest plus explicit confirmation, and rejects unsafe environment or pool configuration before source access. Its empty-source execution and replay rejection passed against PostgreSQL 16.13. A node-postgres adapter, fail-closed production pool and rate-limit configuration contracts, composed-adapter foundation, owned API runtime composition, exact readiness query, and repeatable loopback PostgreSQL 16.13 rehearsal prove contact write/read, tenant-isolated immutable contact-consent history and latest-event projection, consent-filtered all/list/tag campaign audiences with cross-tenant group isolation, tenant-isolated contact organization/import schema, atomic contact-profile plus import-outcome writes, concurrent onboarding first-owner provisioning and receipt replay through the authenticated HTTP path, concurrent tenant-selection save and receipt replay through the authenticated HTTP path, concurrent authenticated team-membership replay, concurrent authenticated team-invitation request replay with one invitation event and one delivery, concurrent authenticated team-invitation acceptance replay with one membership and one acceptance, exact inbound-message replay/conflict with a single unread increment, optimistic inbox read/assignment transitions through the complete authenticated HTTP path with committed-plus-replayed concurrency, delivery-status replay/staleness, concurrent bot-flow draft replay through the authenticated HTTP path, publication replacement and version advancement, concurrent campaign snapshot and activation replay through the authenticated HTTP path, concurrent AI-agent draft replay through the authenticated HTTP path, concurrent AI reply approval replay through the authenticated HTTP path, referentially scoped reply staging and single delivery claim, accepted-button continuation for the immediately previous inbound message, serialized bot handoff replay, deterministic knowledge-source registration, validation/scanning/recovery transitions and atomic passage processing/replay, concurrent AI-agent draft replay, immutable version advancement, source-link verification and publication replacement, serialized AI-runtime cost authorization/usage replay, shared-budget enforcement and audited handoff replay, concurrent AI reply staging and authenticated approval replay, concurrent tenant-subscription creation/extension/status/cancellation replay, concurrent first-owner provisioning replay and identity-collision rejection, concurrent production-decision creation/update replay with immutable event guards, concurrent exact system-admin profile replay and conflicting profile updates with immutable admin-event guards, tenant-bound Meta connection/credential state, webhook claim/replay/conflict behavior, atomic delivery-policy audit/replay/conflict, disable and re-enable behavior, WhatsApp pair/portfolio/phone-throughput reservation replay, settlement, cooldown and tamper rejection, scheduler claim/catch-up/fencing, exact template draft replay, single submission claim and duplicate status-event classification, exact campaign-snapshot replay/conflict/rollback, campaign activation/claim/retry/consent revalidation/completion, concurrent provider acceptance and terminal status reconciliation with immutable evidence and atomic rate settlement, concurrent provider-deferral provenance replay bound to one exact delivery claim, reservation and cooldown, immutable inbound button-reply provenance, immutable Meta 131047 service-window rejection provenance, a concurrent immutable provider-request fence with one accepted delivery and duplicate observation, exact request binding for acceptance, provider deferral, and Meta 131047 rejection, a concurrent kill-switch observation proving one audited enabled-to-disabled policy transition with zero provider requests and zero acceptances, shared mutation token-bucket enforcement, the complete authenticated six-source reporting HTTP path, conversation/message, template/campaign, bot delivery and AI reporting constraints, commit/replay/rollback, invitation delivery/acceptance, and eighty-seven real concurrency scenarios. The inventory contains all 58 ordered PostgreSQL migrations through migration 0057. The 44 migrations through 0043 form the earlier critical-path foundation; migrations 0044-0057 are dormant hardening contracts and do not authorize Runtime activation. The latest live loopback rehearsal passed the first 40 migrations through 0039, the immutable provider-request fence scenario and the kill-switch zero-provider-request scenario; migration 0040 has contract and repository tests, migration 0041 passed direct PostgreSQL 16.13 candidate-to-CAS proof, and migration 0057 passed its dedicated local PostgreSQL 16.13 verifier twice. D31-C1 is dormant-complete; selectedCollectionMode remains null, and no Runtime importer or provider capability is activated. D1e is also dormant-complete and does not authorize Runtime activation. Data migration and semantic-parity contracts for all ten slices and all 55 tables are implemented; a live 55-table rehearsal remains required. A live Railway plan and region, provider-bound pool and rate-limit values, controlled-environment export, signed full rehearsal, PITR proof, staging and load evidence are not implemented. Clerk Dashboard configuration and live Organization evidence are also not implemented.",
  }),
  capability({
    id: "data.object-storage",
    currentBindings: ["FILES"],
    currentResources: ["Cloudflare R2"],
    sourceFiles: [
      ".openai/hosting.json",
      "server/ai/knowledgeObjectStorage.ts",
      "docs/researched-decision-approval-2026-08-26.md",
    ],
    targetPlacement: "shared-managed-service",
    targetContract:
      "Private AWS S3 KnowledgeObjectStorage in il-central-1 with TLS-only access, version-bound malware verdicts, versioning, lifecycle and separated backup/evidence storage",
    targetProvider: "aws-s3",
    decisionState: "selected",
    nextAction: "configuration-required",
    cutoverBlocker:
      "AWS S3 in il-central-1 is selected, but only the R2 adapter and R2-specific evidence exist. No AWS account, private buckets, Block Public Access policy, IAM roles, encryption configuration, versioning, lifecycle, GuardDuty Malware Protection, EventBridge verdict path, checksum migration rehearsal, budget cap or live residency/security evidence has been approved or configured. Object Lock governance may be enabled only for approved data classes; compliance mode remains prohibited until Legal approves its irreversible retention effect.",
  }),
  capability({
    id: "queue.meta-webhook",
    currentBindings: ["META_WEBHOOK_QUEUE"],
    currentResources: [
      "connect-meta-webhooks",
      "connect-meta-webhooks-dlq",
    ],
    sourceFiles: [
      "vite.config.ts",
      "server/meta/metaWebhookQueuePublisher.ts",
      "server/meta/metaWebhookQueueConsumer.ts",
      "server/platform/railwayBullMqConfiguration.ts",
      "server/platform/railwayBullMqMetaWebhookQueue.ts",
      "server/platform/railwayBullMqPostgresApiRuntime.ts",
      "server/platform/railwayBullMqApiMain.ts",
      "server/platform/railwayBullMqWorkerExecutable.ts",
      "server/platform/railwayBullMqWorkerMain.ts",
      "server/platform/railwayWorkerTelemetry.ts",
      "server/platform/railwayBetterStackTelemetry.ts",
      "server/platform/railwayWorkerExecutable.ts",
      "server/platform/railwayPostgresWorkerService.ts",
      "shared/domain/queuePolicy.ts",
      "shared/domain/queueAdapterAcceptance.ts",
      "shared/domain/redisDurabilityAcceptance.ts",
      "scripts/verify-queue-adapter-evidence.mjs",
      "scripts/rehearse-local-redis-resilience.mjs",
      "scripts/start-railway-bullmq-worker.mjs",
      "docs/railway-redis-durability-rehearsal.md",
      "docs/better-stack-opentelemetry.md",
    ],
    targetPlacement: "railway-worker",
    targetContract: "BullMQ MetaWebhookQueueBinding over Railway Redis",
    targetProvider: "railway",
    decisionState: "selected",
    nextAction: "configuration-required",
    cutoverBlocker:
      "Railway Redis with BullMQ is selected. A shared short-lived staging acceptance contract and trusted-file verifier cover batch, retry, acknowledgement, duplicate delivery and DLQ behavior. The local adapter preserves the signed payload through canonical Base64, uses its SHA-256 digest as the deterministic job ID, allows ten retries after the initial delivery, dead-letters poison and exhausted jobs, fails closed when DLQ persistence fails, and connects the API publisher plus the PostgreSQL business consumer to one provider-bound worker. A real local Redis test proves byte-for-byte payload round-trip and duplicate suppression. A separate local Redis 8.6.1 crash rehearsal proves AOF everysec, noeviction, fail-closed publishing during outage, queued-work recovery and 500/500 completed load jobs. The fail-closed package start command composes all four queues and emits bounded structured JSON telemetry locally. Approved live retention and secrets, a production telemetry provider, authorized Railway durability and load evidence, and current-release Railway staging evidence remain unavailable.",
  }),
  capability({
    id: "queue.campaign-delivery",
    currentBindings: ["CAMPAIGN_DELIVERY_QUEUE"],
    currentResources: [
      "connect-campaign-deliveries",
      "connect-campaign-deliveries-dlq",
    ],
    sourceFiles: [
      "vite.config.ts",
      "server/campaigns/campaignScheduler.ts",
      "server/campaigns/campaignDeliveryQueueConsumer.ts",
      "server/campaigns/campaignDeliveryDeadLetter.ts",
      "server/campaigns/providerResponseMetaCampaignDeliveryRetryEvidenceSource.ts",
      "shared/domain/queuePolicy.ts",
      "shared/domain/queueAdapterAcceptance.ts",
      "shared/domain/redisDurabilityAcceptance.ts",
      "scripts/verify-queue-adapter-evidence.mjs",
      "scripts/rehearse-local-redis-resilience.mjs",
      "docs/railway-redis-durability-rehearsal.md",
      "server/platform/railwayBullMqConfiguration.ts",
      "server/platform/railwayBullMqCampaignDeliveryQueue.ts",
      "server/platform/railwayCampaignDeliveryConsumerRuntime.ts",
      "server/platform/railwayBullMqWorkerExecutable.ts",
      "server/platform/railwayBullMqWorkerMain.ts",
      "server/platform/railwayWorkerTelemetry.ts",
      "server/platform/railwayBetterStackTelemetry.ts",
      "server/platform/railwayWorkerExecutable.ts",
      "server/platform/railwayWorkerRuntime.ts",
      "server/platform/railwayPostgresWorkerService.ts",
      "scripts/start-railway-bullmq-worker.mjs",
      "docs/better-stack-opentelemetry.md",
    ],
    targetPlacement: "railway-worker",
    targetContract: "BullMQ CampaignDeliveryQueueBinding over Railway Redis",
    targetProvider: "railway",
    decisionState: "selected",
    nextAction: "configuration-required",
    cutoverBlocker:
      "Railway Redis with BullMQ is selected. A shared short-lived staging acceptance contract and trusted-file verifier cover batch publish, delayed retry, duplicate delivery and DLQ behavior. The local fail-closed BullMQ v5 adapter now implements deterministic batches of ten, ten retries after the initial delivery, per-delivery delayed retry up to 24 hours without jitter, poison and exhausted-work DLQ routing, bounded retention cleanup and graceful lifecycle. A real local Redis test proved the dynamic delayed retry and acknowledgement path. A separate local Redis 8.6.1 crash rehearsal proves AOF everysec, noeviction, fail-closed publishing during outage, queued-work recovery and 500/500 completed load jobs. The provider-bound PostgreSQL composition uses the persisted WhatsApp reservation ledger, keeps ambiguous Meta outcomes out of automatic retry, starts all four BullMQ queues before the scheduler, cleans all four DLQs under the fenced lease and closes Redis before PostgreSQL. A provider-response Meta retry-evidence source implements bounded handling for codes 130429, 131049 and 131056 without inventing Retry-After, and the fail-closed package start command wires it into the Worker. Approved retention values, a production telemetry provider, authorized Railway durability/load evidence, live credentials, live-account retry validation and current-release Railway staging acceptance proof remain unavailable.",
  }),
  capability({
    id: "queue.team-invitation",
    currentBindings: ["TEAM_INVITATION_QUEUE"],
    currentResources: [
      "connect-team-invitations",
      "connect-team-invitations-dlq",
    ],
    sourceFiles: [
      "vite.config.ts",
      "server/team/teamInvitationQueuePublisher.ts",
      "server/team/teamInvitationQueueConsumer.ts",
      "server/team/teamInvitationDispatchProcessor.ts",
      "server/platform/postgresTeamInvitationDeliveryRepository.ts",
      "server/platform/clerkRailwayTeamInvitationProvider.ts",
      "server/platform/railwayTeamInvitationProviderFactory.ts",
      "server/platform/postgresMutationRateLimitConfiguration.ts",
      "postgres/migrations/0028_clerk_invitation_rate_limit.sql",
      "postgres/migrations/0029_team_invitation_delivery_deferrals.sql",
      "server/platform/railwayBullMqConfiguration.ts",
      "server/platform/railwayBullMqTeamInvitationQueue.ts",
      "server/platform/railwayBullMqPostgresApiRuntime.ts",
      "server/platform/railwayBullMqApiMain.ts",
      "server/platform/railwayBullMqWorkerExecutable.ts",
      "server/platform/railwayBullMqWorkerMain.ts",
      "server/platform/railwayWorkerTelemetry.ts",
      "server/platform/railwayBetterStackTelemetry.ts",
      "server/platform/railwayWorkerExecutable.ts",
      "server/platform/railwayPostgresWorkerService.ts",
      "docs/railway-bullmq-team-invitation-adapter.md",
      "shared/domain/queuePolicy.ts",
      "shared/domain/queueAdapterAcceptance.ts",
      "shared/domain/redisDurabilityAcceptance.ts",
      "scripts/verify-queue-adapter-evidence.mjs",
      "scripts/rehearse-local-redis-resilience.mjs",
      "scripts/start-railway-bullmq-worker.mjs",
      "docs/railway-redis-durability-rehearsal.md",
      "docs/better-stack-opentelemetry.md",
    ],
    targetPlacement: "railway-worker",
    targetContract: "BullMQ TeamInvitationQueueBinding over Railway Redis",
    targetProvider: "railway",
    decisionState: "selected",
    nextAction: "configuration-required",
    cutoverBlocker:
      "Railway Redis with BullMQ is selected. A shared short-lived staging acceptance contract and trusted-file verifier cover bounded retry, acknowledgement isolation, duplicate delivery and DLQ behavior. The local fail-closed adapter uses the persisted delivery key as its deterministic job ID, allows ten retries after the initial delivery, preserves bounded delays from 1 second through 24 hours without jitter, dead-letters poison and exhausted jobs, fails closed when DLQ persistence fails, and cleans bounded retention under the fenced worker. The API publisher and PostgreSQL dispatch consumer are connected, and a real local Redis test proves separate-process delivery and duplicate suppression. A separate local Redis 8.6.1 crash rehearsal proves AOF everysec, noeviction, fail-closed publishing during outage, queued-work recovery and 500/500 completed load jobs. The local Clerk Organization provider adapter enforces 72-hour expiry, authoritative Tenant binding, deterministic private-metadata reconciliation, bounded fail-closed pagination and a required shared creation guard. Valid Clerk 429 responses now persist exact Retry-After evidence before atomically releasing the delivery claim; missing or invalid Retry-After is never invented. Early replay reads the durable deferral and does not call Clerk again. Its Worker factory is connected to the authoritative Organization repository and a dedicated shared PostgreSQL guard that is bounded below Clerk's official endpoint budget and configured without defaults. The fail-closed package start command validates the live Identity and shared-rate-limit configuration before opening Worker connections. Approved live policy values, live Clerk 429 evidence, approved retention values, a production telemetry provider, authorized Railway durability/load evidence and current-release Railway staging evidence remain unavailable.",
  }),
  capability({
    id: "queue.message-template-submission",
    currentBindings: [],
    currentResources: [
      "provider-neutral message template submission queue contract",
    ],
    sourceFiles: [
      "server/templates/messageTemplateSubmissionQueueMessage.ts",
      "server/templates/messageTemplateSubmissionQueueConsumer.ts",
      "shared/domain/queuePolicy.ts",
      "shared/domain/queueAdapterAcceptance.ts",
      "shared/domain/redisDurabilityAcceptance.ts",
      "scripts/verify-queue-adapter-evidence.mjs",
      "scripts/rehearse-local-redis-resilience.mjs",
      "server/templates/messageTemplateSubmissionMaintenanceRunner.ts",
      "server/operations/messageTemplateSubmissionMaintenanceTelemetry.ts",
      "server/platform/railwayMessageTemplateSubmissionWorkerRuntime.ts",
      "server/platform/railwayMessageTemplateSubmissionMaintenanceRuntime.ts",
      "server/platform/railwayBullMqConfiguration.ts",
      "server/platform/railwayBullMqMessageTemplateSubmissionQueue.ts",
      "server/platform/railwayBullMqMessageTemplateSubmissionWorkerExecutable.ts",
      "server/platform/railwayBullMqCampaignDeliveryQueue.ts",
      "server/platform/railwayCampaignDeliveryConsumerRuntime.ts",
      "server/platform/railwayBullMqWorkerExecutable.ts",
      "server/platform/railwayBullMqWorkerMain.ts",
      "server/platform/railwayWorkerTelemetry.ts",
      "server/platform/railwayBetterStackTelemetry.ts",
      "server/platform/railwayWorkerExecutable.ts",
      "server/platform/railwayPostgresWorkerService.ts",
      "docs/railway-bullmq-message-template-submission-adapter.md",
      "docs/railway-redis-durability-rehearsal.md",
      "docs/better-stack-opentelemetry.md",
      "scripts/start-railway-bullmq-worker.mjs",
    ],
    targetPlacement: "railway-worker",
    targetContract:
      "BullMQ at-least-once bounded template submission delivery over Railway Redis with DLQ and read-only reconciliation",
    targetProvider: "railway",
    decisionState: "selected",
    nextAction: "configuration-required",
    cutoverBlocker:
      "Railway Redis with BullMQ is selected. The bounded queue message, consumer, single-POST worker, at-least-once relay, GET-only reconciliation, scheduler wiring, identity-free maintenance telemetry, shared short-lived staging acceptance contract and trusted-file verifier exist locally. Migration 0026 and the outbox lifecycle are proven against local PostgreSQL 16.13. A fail-closed BullMQ v5 adapter implements deterministic publish, ten retries after the initial delivery, fixed delayed retry without jitter, poison and exhausted-work DLQ routing, bounded retention cleanup, dual-stack Railway-private Redis configuration and graceful lifecycle; its real local Redis publish/consume/deduplication test passed. A separate local Redis 8.6.1 crash rehearsal proves AOF everysec, noeviction, fail-closed publishing during outage, queued-work recovery and 500/500 completed load jobs. The provider-bound composition now creates the consumer from PostgreSQL, starts all four queues before the scheduler, runs bounded DLQ cleanup with maintenance, drains BullMQ before PostgreSQL and closes partial startup resources. A fail-closed package start command and bounded local structured telemetry are implemented. Approved retention values, a production telemetry provider, authorized Railway durability/load evidence, live credentials and current-release Railway staging proof remain unavailable.",
  }),
  capability({
    id: "worker.scheduler",
    currentBindings: [],
    currentResources: ["Cloudflare Cron */1 minute"],
    sourceFiles: [
      "vite.config.ts",
      "worker/index.ts",
      "server/campaigns/campaignDispatchRuntime.ts",
      "server/team/teamInvitationExpirationRuntime.ts",
      "shared/domain/workerScheduler.ts",
      "server/platform/postgresWorkerSchedulerLeaseRepository.ts",
      "server/platform/railwayWorkerScheduler.ts",
      "server/platform/railwayWorkerSchedulerService.ts",
      "server/platform/railwayWorkerProcess.ts",
      "server/platform/railwayWorkerMain.ts",
      "server/platform/railwayWorkerExecutable.ts",
      "server/platform/railwayBullMqMessageTemplateSubmissionWorkerExecutable.ts",
      "server/platform/railwayBullMqCampaignDeliveryQueue.ts",
      "server/platform/railwayCampaignDeliveryConsumerRuntime.ts",
      "server/platform/railwayBullMqWorkerExecutable.ts",
      "server/platform/railwayBullMqWorkerMain.ts",
      "server/platform/railwayBotReplyStagingActivationPreflight.ts",
      "server/platform/railwayWorkerTelemetry.ts",
      "server/platform/railwayBetterStackTelemetry.ts",
      "server/platform/railwayWorkerRuntime.ts",
      "server/platform/railwayPostgresWorkerService.ts",
      "server/platform/postgresCampaignDispatchRepository.ts",
      "server/templates/messageTemplateSubmissionMaintenanceRunner.ts",
      "server/operations/messageTemplateSubmissionMaintenanceTelemetry.ts",
      "server/platform/railwayMessageTemplateSubmissionMaintenanceRuntime.ts",
      "server/platform/postgresMessageTemplateSubmissionOutboxRepository.ts",
      "server/platform/clerkRailwayTeamInvitationProvider.ts",
      "server/platform/postgresTeamInvitationDeliveryRepository.ts",
      "server/platform/postgresMutationRateLimitConfiguration.ts",
      "server/campaigns/providerResponseMetaCampaignDeliveryRetryEvidenceSource.ts",
      "scripts/start-railway-bullmq-worker.mjs",
      "scripts/verify-bot-reply-staging-activation.mjs",
      "docs/better-stack-opentelemetry.md",
      "postgres/migrations/0014_worker_scheduler_lease.sql",
      "postgres/migrations/0015_campaign_dispatch.sql",
      "postgres/migrations/0026_message_template_submission_outbox.sql",
      "postgres/migrations/0029_team_invitation_delivery_deferrals.sql",
    ],
    targetPlacement: "railway-worker",
    targetContract:
      "Always-on one-minute scheduler with an atomic PostgreSQL lease and bounded catch-up",
    targetProvider: "railway",
    decisionState: "selected",
    nextAction: "configuration-required",
    cutoverBlocker:
      "Railway Cron cannot satisfy the one-minute cadence. The atomic PostgreSQL lease, fencing token, campaign/invitation orchestrator, five-tick catch-up, minute-aligned timer, overlap suppression, active-run drain, SIGINT/SIGTERM process lifecycle and PostgreSQL runtime composition are implemented. The provider-neutral template-submission maintenance cycle is wired as an optional task and emits bounded identity-free telemetry. A fail-closed provider-neutral bootstrap validates the scheduler owner, isolates telemetry and closes the service after partial startup failure. One provider-bound process owns the four baseline BullMQ queues: Campaign, Template submission, Meta webhook and Team invitation, including fenced DLQ cleanup. A fifth Bot reply staging queue is composed only when BOT_REPLY_STAGING_ENABLED is exactly true and a shared seven-check activation preflight verifies its private, telemetry and safety configuration before Worker startup without returning configuration values. Its package start command binds the local Clerk Organization provider, the shared PostgreSQL creation guard, provider-response Meta retry policy and bounded structured JSON telemetry; it rejects incomplete Identity or rate-limit configuration before opening Worker connections. Valid Clerk 429 responses now persist exact bounded Retry-After evidence before releasing the claim, and early replay does not call Clerk again. A production telemetry provider, approved live policy and retention values, live Clerk 429 evidence, live Railway configuration and current-release Staging evidence remain unavailable.",
  }),
  capability({
    id: "security.distributed-rate-limits",
    currentBindings: [
      "META_WEBHOOK_RATE_LIMITER",
      "TENANT_MUTATION_RATE_LIMITER",
      "SYSTEM_ADMIN_MUTATION_RATE_LIMITER",
    ],
    currentResources: [
      "Cloudflare Rate Limit bindings",
      "D1 WhatsApp reservation ledger",
    ],
    sourceFiles: [
      "server/security/rateLimit.ts",
      "db/whatsappRateLimitRepository.ts",
      "postgres/migrations/0023_api_mutation_rate_limits.sql",
      "postgres/migrations/0024_whatsapp_legacy_reservation_category.sql",
      "server/platform/postgresMutationRateLimitBinding.ts",
      "server/platform/postgresMutationRateLimitConfiguration.ts",
      "server/platform/railwayMetaWebhookRuntime.ts",
      "server/platform/railwayPostgresApiRuntime.ts",
      "worker/index.ts",
    ],
    targetPlacement: "shared-managed-service",
    targetContract:
      "Live-Meta-derived layered limits using Railway PostgreSQL and Redis",
    targetProvider: "railway",
    decisionState: "selected",
    nextAction: "configuration-required",
    cutoverBlocker:
      "The live-derived layered policy is selected. PostgreSQL provides one atomic shared token-bucket contract with isolated, versioned tenant-mutation, system-admin-mutation and Meta-webhook policies; the existing PostgreSQL ledger covers WhatsApp reservations. Tenant mutations and the optional Meta webhook route have local Railway composition. Current WABA and phone values, approved Connect quotas, system-admin route wiring, telemetry, kill-switch rehearsal and load evidence still lack a complete distributed target proof.",
  }),
  capability({
    id: "security.secret-management",
    currentBindings: [
      "META_APP_SECRET",
      "META_WEBHOOK_VERIFY_TOKEN",
      "WHATSAPP_RATE_LIMIT_HMAC_KEY_V1",
    ],
    currentResources: ["Cloudflare Worker secrets"],
    sourceFiles: [
      "worker/index.ts",
      "server/operations/productionReadiness.ts",
    ],
    targetPlacement: "vercel-web+railway-api+railway-worker",
    targetContract:
      "Purpose-separated secret inventory with rotation evidence",
    targetProvider: "vercel+railway",
    decisionState: "selected",
    nextAction: "configuration-required",
    cutoverBlocker:
      "Secret ownership, placement, rotation, and cross-service access are not configured.",
  }),
  capability({
    id: "operations.environment-isolation-evidence",
    currentBindings: [],
    currentResources: ["Cloudflare environment isolation evidence v2"],
    sourceFiles: [
      "server/operations/environmentIsolationEvidence.ts",
      "scripts/create-cloudflare-evidence.mjs",
    ],
    targetPlacement: "vercel+railway",
    targetContract:
      "Provider-neutral environment isolation evidence",
    targetProvider: "vercel+railway",
    decisionState: "selected",
    nextAction: "evidence-rebuild-required",
    cutoverBlocker:
      "The verifier fingerprints only Cloudflare resources and deployments.",
  }),
  capability({
    id: "operations.deployment-provenance-evidence",
    currentBindings: [],
    currentResources: ["Cloudflare deployment provenance"],
    sourceFiles: [
      "server/operations/deploymentProvenanceEvidence.ts",
      "scripts/create-cloudflare-evidence.mjs",
    ],
    targetPlacement: "vercel+railway",
    targetContract:
      "Release-bound multi-service deployment provenance",
    targetProvider: "vercel+railway",
    decisionState: "selected",
    nextAction: "evidence-rebuild-required",
    cutoverBlocker:
      "No evidence links one release to Vercel Web and both Railway services.",
  }),
  capability({
    id: "operations.backup-restore",
    currentBindings: [],
    currentResources: ["D1 and R2 backup evidence v2"],
    sourceFiles: [
      "server/operations/backupRestoreEvidence.ts",
      "docs/external-decisions-recommendations.md",
    ],
    targetPlacement: "shared-managed-service",
    targetContract:
      "PostgreSQL and object storage backup/restore evidence",
    targetProvider: "unknown/unavailable",
    decisionState: "decision-required",
    nextAction: "provider-decision-required",
    cutoverBlocker:
      "The database, storage, PITR window, backup region, and restore path are not selected.",
  }),
  capability({
    id: "operations.browser-database-proof",
    currentBindings: [],
    currentResources: ["Cloudflare D1 read-only proof API"],
    sourceFiles: [
      "db/teamInvitationBrowserProofReader.ts",
      "scripts/run-team-invitation-browser-e2e.mjs",
    ],
    targetPlacement: "shared-managed-service",
    targetContract:
      "Read-only PostgreSQL browser acceptance proof",
    targetProvider: "unknown/unavailable",
    decisionState: "decision-required",
    nextAction: "adapter-required",
    cutoverBlocker:
      "Browser evidence can currently query only Cloudflare D1.",
  }),
  capability({
    id: "operations.observability",
    currentBindings: [],
    currentResources: ["Cloudflare Workers logs and traces recommendation"],
    sourceFiles: [
      "server/operations/sloMonitoringService.ts",
      "server/operations/operationalTelemetry.ts",
      "server/operations/teamInvitationDeliveryTelemetry.ts",
      "server/templates/messageTemplateSubmissionWorker.ts",
      "server/platform/railwayWorkerTelemetry.ts",
      "server/platform/betterStackOtlpLogs.ts",
      "server/platform/betterStackOtlpApiSignals.ts",
      "server/platform/betterStackOtlpWorkerSignals.ts",
      "server/platform/deterministicOtlpIds.ts",
      "server/platform/railwayBetterStackTelemetry.ts",
      "server/platform/railwayMessageTemplateSubmissionWorkerRuntime.ts",
      "server/platform/railwayPostgresWorkerService.ts",
      "server/platform/vercelBetterStackTelemetry.ts",
      "server/platform/w3cTraceContext.ts",
      "server/platform/currentVercelOpaqueTraceContext.ts",
      "server/platform/railwayApiClient.ts",
      "server/platform/railwayApiHttpHandler.ts",
      "scripts/start-railway-bullmq-worker.mjs",
      "server/platform/railwayBullMqApiMain.ts",
      "scripts/start-railway-bullmq-api.mjs",
      "docs/external-decisions-recommendations.md",
      "docs/better-stack-opentelemetry.md",
    ],
    targetPlacement: "vercel+railway",
    targetContract:
      "PII-safe cross-service logs, metrics, traces, SLOs, and alerts",
    targetProvider: "better-stack",
    decisionState: "selected",
    nextAction: "adapter-required",
    cutoverBlocker:
      "Better Stack with OpenTelemetry is selected. The Railway Worker, Railway API and Vercel Web have local OTLP Logs exporters with structural redaction, bounded batching and HTTPS endpoint validation; Vercel schedules forceFlush through the Next.js after-response lifecycle. Vercel derives an opaque W3C trace context from its platform request ID with a Vercel-only HMAC key and propagates it only to the fixed OIDC-authenticated Railway API. The API path emits a deterministic Vercel root client span, Railway child server span, request counter and duration histogram with bounded attributes. The Worker emits deterministic root spans for validated timed operations plus bounded event, operation duration, provider duration and item metrics covering the four baseline queues and the explicitly enabled Bot reply staging queue. Team invitation and message-template submission emit per-delivery consumer spans; the measured Meta template POST emits a deterministic client child span under its delivery without URL, tenant, template, WABA or payload attributes. Logs attach their local native span context without identity or payload attributes. Provider child spans for campaign delivery, reconciliation and Clerk, verified live ingestion and correlation, retention, alert channel, named on-call rotation, cost cap and staging proof remain unavailable.",
  }),
] satisfies readonly Readonly<HostingMigrationCapability>[]);
